export type { BodyDubsAllOrSomeSegmentsAndLanguagesV1DubbingResourceDubbingIdDubPost } from "./BodyDubsAllOrSomeSegmentsAndLanguagesV1DubbingResourceDubbingIdDubPost";
export type { BodyMoveSegmentsBetweenSpeakersV1DubbingResourceDubbingIdMigrateSegmentsPost } from "./BodyMoveSegmentsBetweenSpeakersV1DubbingResourceDubbingIdMigrateSegmentsPost";
export type { BodyRenderAudioOrVideoForTheGivenLanguageV1DubbingResourceDubbingIdRenderLanguagePost } from "./BodyRenderAudioOrVideoForTheGivenLanguageV1DubbingResourceDubbingIdRenderLanguagePost";
export type { BodyTranscribesSegmentsV1DubbingResourceDubbingIdTranscribePost } from "./BodyTranscribesSegmentsV1DubbingResourceDubbingIdTranscribePost";
export type { BodyTranslatesAllOrSomeSegmentsAndLanguagesV1DubbingResourceDubbingIdTranslatePost } from "./BodyTranslatesAllOrSomeSegmentsAndLanguagesV1DubbingResourceDubbingIdTranslatePost";
