// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";

export const BodyGenerateCompositionPlanV1MusicPlanPostModelId: core.serialization.Schema<
    serializers.music.BodyGenerateCompositionPlanV1MusicPlanPostModelId.Raw,
    ElevenLabs.music.BodyGenerateCompositionPlanV1MusicPlanPostModelId
> = core.serialization.enum_(["music_v1", "music_v2"]);

export declare namespace BodyGenerateCompositionPlanV1MusicPlanPostModelId {
    export type Raw = "music_v1" | "music_v2";
}
