/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as fs from "fs";

/**
 * @example
 *     {
 *         file: fs.createReadStream("/path/to/your/file"),
 *         text: "text"
 *     }
 */
export interface BodyCreateForcedAlignmentV1ForcedAlignmentPost {
    file: File | fs.ReadStream | Blob;
    /** The text to align with the audio. The input text can be in any format, however diarization is not supported at this time. */
    text: string;
}
