// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as serializers from "../../../../serialization/index.js";
import * as ElevenLabs from "../../../index.js";

export declare namespace SpeechToSpeechClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SpeechToSpeechClient {
    protected readonly _options: NormalizedClientOptions<SpeechToSpeechClient.Options>;

    constructor(options: SpeechToSpeechClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Transform audio from one voice to another. Maintain full control over emotion, timing and delivery.
     *
     * @throws {@link ElevenLabs.UnprocessableEntityError}
     * @throws {@link errors.ElevenLabsError}
     * @throws {@link errors.ElevenLabsTimeoutError}
     */
    public convert(
        voice_id: string,
        request: ElevenLabs.BodySpeechToSpeechV1SpeechToSpeechVoiceIdPost,
        requestOptions?: SpeechToSpeechClient.RequestOptions,
    ): core.HttpResponsePromise<ReadableStream<Uint8Array>> {
        return core.HttpResponsePromise.fromPromise(this.__convert(voice_id, request, requestOptions));
    }

    private async __convert(
        voice_id: string,
        request: ElevenLabs.BodySpeechToSpeechV1SpeechToSpeechVoiceIdPost,
        requestOptions?: SpeechToSpeechClient.RequestOptions,
    ): Promise<core.WithRawResponse<ReadableStream<Uint8Array>>> {
        const _queryParams: Record<string, unknown> = {
            enable_logging: request.enableLogging,
            optimize_streaming_latency: request.optimizeStreamingLatency,
            output_format:
                request.outputFormat != null
                    ? serializers.ConvertSpeechToSpeechRequestOutputFormat.jsonOrThrow(request.outputFormat, {
                          unrecognizedObjectKeys: "strip",
                          omitUndefined: true,
                      })
                    : undefined,
        };
        const _body = await core.newFormData();
        await _body.appendFile("audio", request.audio);
        if (request.modelId != null) {
            _body.append("model_id", request.modelId);
        }

        if (request.voiceSettings != null) {
            _body.append("voice_settings", request.voiceSettings);
        }

        if (request.seed != null) {
            _body.append("seed", request.seed?.toString());
        }

        if (request.removeBackgroundNoise != null) {
            _body.append("remove_background_noise", request.removeBackgroundNoise?.toString());
        }

        if (request.fileFormat != null) {
            _body.append(
                "file_format",
                serializers.SpeechToSpeechRequestFileFormat.jsonOrThrow(request.fileFormat, {
                    unrecognizedObjectKeys: "strip",
                    omitUndefined: true,
                }),
            );
        }

        const _maybeEncodedRequest = await _body.getRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "xi-api-key": requestOptions?.apiKey ?? this._options?.apiKey ?? process.env?.ELEVENLABS_API_KEY,
                ..._maybeEncodedRequest.headers,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)<ReadableStream<Uint8Array>>({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ElevenLabsEnvironment.Production,
                `v1/speech-to-speech/${core.url.encodePathParam(voice_id)}`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            requestType: "file",
            duplex: _maybeEncodedRequest.duplex,
            body: _maybeEncodedRequest.body,
            responseType: "streaming",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 240) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new ElevenLabs.UnprocessableEntityError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.ElevenLabsError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/speech-to-speech/{voice_id}",
        );
    }

    /**
     * Stream audio from one voice to another. Maintain full control over emotion, timing and delivery.
     *
     * @throws {@link ElevenLabs.UnprocessableEntityError}
     * @throws {@link errors.ElevenLabsError}
     * @throws {@link errors.ElevenLabsTimeoutError}
     */
    public stream(
        voice_id: string,
        request: ElevenLabs.BodySpeechToSpeechStreamingV1SpeechToSpeechVoiceIdStreamPost,
        requestOptions?: SpeechToSpeechClient.RequestOptions,
    ): core.HttpResponsePromise<ReadableStream<Uint8Array>> {
        return core.HttpResponsePromise.fromPromise(this.__stream(voice_id, request, requestOptions));
    }

    private async __stream(
        voice_id: string,
        request: ElevenLabs.BodySpeechToSpeechStreamingV1SpeechToSpeechVoiceIdStreamPost,
        requestOptions?: SpeechToSpeechClient.RequestOptions,
    ): Promise<core.WithRawResponse<ReadableStream<Uint8Array>>> {
        const _queryParams: Record<string, unknown> = {
            enable_logging: request.enableLogging,
            optimize_streaming_latency: request.optimizeStreamingLatency,
            output_format:
                request.outputFormat != null
                    ? serializers.StreamSpeechToSpeechRequestOutputFormat.jsonOrThrow(request.outputFormat, {
                          unrecognizedObjectKeys: "strip",
                          omitUndefined: true,
                      })
                    : undefined,
        };
        const _body = await core.newFormData();
        await _body.appendFile("audio", request.audio);
        if (request.modelId != null) {
            _body.append("model_id", request.modelId);
        }

        if (request.voiceSettings != null) {
            _body.append("voice_settings", request.voiceSettings);
        }

        if (request.seed != null) {
            _body.append("seed", request.seed?.toString());
        }

        if (request.removeBackgroundNoise != null) {
            _body.append("remove_background_noise", request.removeBackgroundNoise?.toString());
        }

        if (request.fileFormat != null) {
            _body.append(
                "file_format",
                serializers.SpeechToSpeechStreamRequestFileFormat.jsonOrThrow(request.fileFormat, {
                    unrecognizedObjectKeys: "strip",
                    omitUndefined: true,
                }),
            );
        }

        const _maybeEncodedRequest = await _body.getRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "xi-api-key": requestOptions?.apiKey ?? this._options?.apiKey ?? process.env?.ELEVENLABS_API_KEY,
                ..._maybeEncodedRequest.headers,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)<ReadableStream<Uint8Array>>({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ElevenLabsEnvironment.Production,
                `v1/speech-to-speech/${core.url.encodePathParam(voice_id)}/stream`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            requestType: "file",
            duplex: _maybeEncodedRequest.duplex,
            body: _maybeEncodedRequest.body,
            responseType: "streaming",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 240) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new ElevenLabs.UnprocessableEntityError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.ElevenLabsError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/speech-to-speech/{voice_id}/stream",
        );
    }
}
