/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElevenLabs from "../../../../../../index";

/**
 * @example
 *     {
 *         simulation_specification: {
 *             simulated_user_config: {
 *                 first_message: "Hello, how can I help you today?",
 *                 language: "en"
 *             }
 *         }
 *     }
 */
export interface BodySimulatesAConversationV1ConvaiAgentsAgentIdSimulateConversationPost {
    /** A specification detailing how the conversation should be simulated */
    simulation_specification: ElevenLabs.ConversationSimulationSpecification;
    /** A list of evaluation criteria to test */
    extra_evaluation_criteria?: ElevenLabs.PromptEvaluationCriteria[];
}
