// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         name: "name",
 *         content: "content",
 *         type: "free_form"
 *     }
 */
export interface UpdateProcedureDraftRequestModel {
    /** Procedure name */
    name: string;
    /** Procedure content */
    content: string;
    /** Procedure type */
    type: ElevenLabs.ProcedureType;
    /** When the agent should use this procedure. Empty string means this is a sub-procedure that should only start when another procedure references it. If omitted or null, the trigger is derived from the content instead. Also accepts `description` as an alias. */
    trigger?: string;
}
