/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "name",
 *         secret_value: "secret_value"
 *     }
 */
export interface BodyAddASecretToTheAgentWhichCanBeReferencedInToolCallsV1ConvaiAgentsAgentIdAddSecretPost {
    /** A name to help identify a particular agent secret */
    name: string;
    /** A value to be encrypted and used by the agent */
    secret_value: string;
}
