// This file was auto-generated by Fern from our API Definition.

/** Voice category used for filtering */
export const GetSharedVoicesRequestCategory = {
    Professional: "professional",
    Famous: "famous",
    HighQuality: "high_quality",
} as const;
export type GetSharedVoicesRequestCategory =
    (typeof GetSharedVoicesRequestCategory)[keyof typeof GetSharedVoicesRequestCategory];
