// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../../index.js";

/**
 * The type of auth connection config
 */
export type CreateAuthConnectionsResponse =
    | ElevenLabs.workspace.CreateAuthConnectionsResponse.Oauth2ClientCredentials
    | ElevenLabs.workspace.CreateAuthConnectionsResponse.RefreshTokenAuth
    | ElevenLabs.workspace.CreateAuthConnectionsResponse.BasicAuth
    | ElevenLabs.workspace.CreateAuthConnectionsResponse.BearerAuth
    | ElevenLabs.workspace.CreateAuthConnectionsResponse.Oauth2Jwt
    | ElevenLabs.workspace.CreateAuthConnectionsResponse.PrivateKeyJwt
    | ElevenLabs.workspace.CreateAuthConnectionsResponse.Mtls
    | ElevenLabs.workspace.CreateAuthConnectionsResponse.CustomHeaderAuth
    | ElevenLabs.workspace.CreateAuthConnectionsResponse.ApiIntegrationOauth2AuthCode
    | ElevenLabs.workspace.CreateAuthConnectionsResponse.ApiIntegrationOauth2CustomApp
    | ElevenLabs.workspace.CreateAuthConnectionsResponse.WhatsappAuth
    | ElevenLabs.workspace.CreateAuthConnectionsResponse.SlackBotAuth
    | ElevenLabs.workspace.CreateAuthConnectionsResponse.UrlSecret;

export namespace CreateAuthConnectionsResponse {
    export interface Oauth2ClientCredentials extends ElevenLabs.OAuth2ClientCredsResponse {
        authType: "oauth2_client_credentials";
    }

    export interface RefreshTokenAuth extends ElevenLabs.RefreshTokenAuthResponse {
        authType: "refresh_token_auth";
    }

    export interface BasicAuth extends ElevenLabs.BasicAuthResponse {
        authType: "basic_auth";
    }

    export interface BearerAuth extends ElevenLabs.BearerAuthResponse {
        authType: "bearer_auth";
    }

    export interface Oauth2Jwt extends ElevenLabs.OAuth2JwtResponse {
        authType: "oauth2_jwt";
    }

    export interface PrivateKeyJwt extends ElevenLabs.PrivateKeyJwtResponse {
        authType: "private_key_jwt";
    }

    export interface Mtls extends ElevenLabs.MtlsAuthResponse {
        authType: "mtls";
    }

    export interface CustomHeaderAuth extends ElevenLabs.CustomHeaderAuthResponse {
        authType: "custom_header_auth";
    }

    export interface ApiIntegrationOauth2AuthCode extends ElevenLabs.ApiIntegrationOAuth2AuthCodeResponse {
        authType: "api_integration_oauth2_auth_code";
    }

    export interface ApiIntegrationOauth2CustomApp extends ElevenLabs.ApiIntegrationOAuth2CustomAppResponse {
        authType: "api_integration_oauth2_custom_app";
    }

    export interface WhatsappAuth extends ElevenLabs.WhatsAppAuthResponse {
        authType: "whatsapp_auth";
    }

    export interface SlackBotAuth extends ElevenLabs.SlackBotAuthResponse {
        authType: "slack_bot_auth";
    }

    export interface UrlSecret extends ElevenLabs.UrlSecretAuthResponse {
        authType: "url_secret";
    }
}
