// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../../../../../../api/index";
import * as core from "../../../../../../../../../core";
import type * as serializers from "../../../../../../../../index";

export const AssignConversationTagsRequestModel: core.serialization.Schema<
    serializers.conversationalAi.conversations.AssignConversationTagsRequestModel.Raw,
    ElevenLabs.conversationalAi.conversations.AssignConversationTagsRequestModel
> = core.serialization.object({
    tagIds: core.serialization.property("tag_ids", core.serialization.list(core.serialization.string())),
});

export declare namespace AssignConversationTagsRequestModel {
    export interface Raw {
        tag_ids: string[];
    }
}
