// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../../../../../api/index.js";
import * as core from "../../../../../../../../core/index.js";
import type * as serializers from "../../../../../../../index.js";

export const TextSearchMessagesRequestSummaryMode: core.serialization.Schema<
    serializers.agents.conversations.TextSearchMessagesRequestSummaryMode.Raw,
    ElevenLabs.agents.conversations.TextSearchMessagesRequestSummaryMode
> = core.serialization.enum_(["exclude", "include"]);

export declare namespace TextSearchMessagesRequestSummaryMode {
    export type Raw = "exclude" | "include";
}
