// This file was auto-generated by Fern from our API Definition.

/**
 * Maximum concurrent text-to-speech/speech-to-speech requests for this API key. Only available for enterprise customers.
 */
export type BodyEditServiceAccountApiKeyV1ServiceAccountsServiceAccountUserIdApiKeysApiKeyIdPatchTtsConcurrencyLimit =
    | number
    | "clear"
    | "no_update";
