// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";
import { CreateBasicAuthRequest } from "../../../../../types/CreateBasicAuthRequest";
import { CreateCustomHeaderAuthRequest } from "../../../../../types/CreateCustomHeaderAuthRequest";
import { CreateOAuth2ClientCredsRequest } from "../../../../../types/CreateOAuth2ClientCredsRequest";
import { CreateOAuth2JwtRequest } from "../../../../../types/CreateOAuth2JwtRequest";
import { CreatePrivateKeyJwtRequest } from "../../../../../types/CreatePrivateKeyJwtRequest";

export const AuthConnectionsCreateRequestBody: core.serialization.Schema<
    serializers.workspace.AuthConnectionsCreateRequestBody.Raw,
    ElevenLabs.workspace.AuthConnectionsCreateRequestBody
> = core.serialization
    .union(core.serialization.discriminant("authType", "auth_type"), {
        oauth2_client_credentials: CreateOAuth2ClientCredsRequest,
        custom_header_auth: CreateCustomHeaderAuthRequest,
        basic_auth: CreateBasicAuthRequest,
        oauth2_jwt: CreateOAuth2JwtRequest,
        private_key_jwt: CreatePrivateKeyJwtRequest,
    })
    .transform<ElevenLabs.workspace.AuthConnectionsCreateRequestBody>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace AuthConnectionsCreateRequestBody {
    export type Raw =
        | AuthConnectionsCreateRequestBody.Oauth2ClientCredentials
        | AuthConnectionsCreateRequestBody.CustomHeaderAuth
        | AuthConnectionsCreateRequestBody.BasicAuth
        | AuthConnectionsCreateRequestBody.Oauth2Jwt
        | AuthConnectionsCreateRequestBody.PrivateKeyJwt;

    export interface Oauth2ClientCredentials extends CreateOAuth2ClientCredsRequest.Raw {
        auth_type: "oauth2_client_credentials";
    }

    export interface CustomHeaderAuth extends CreateCustomHeaderAuthRequest.Raw {
        auth_type: "custom_header_auth";
    }

    export interface BasicAuth extends CreateBasicAuthRequest.Raw {
        auth_type: "basic_auth";
    }

    export interface Oauth2Jwt extends CreateOAuth2JwtRequest.Raw {
        auth_type: "oauth2_jwt";
    }

    export interface PrivateKeyJwt extends CreatePrivateKeyJwtRequest.Raw {
        auth_type: "private_key_jwt";
    }
}
