// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         agentId: "agent_id"
 *     }
 */
export interface ListWhatsappAccountsRequest {
    /** Filter by assigned agent ID */
    agentId?: string;
}
