export { BodyCreateANewSpeakerV1DubbingResourceDubbingIdSpeakerPost } from "./BodyCreateANewSpeakerV1DubbingResourceDubbingIdSpeakerPost";
export { BodyUpdateMetadataForASpeakerV1DubbingResourceDubbingIdSpeakerSpeakerIdPatch } from "./BodyUpdateMetadataForASpeakerV1DubbingResourceDubbingIdSpeakerSpeakerIdPatch";
