/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../../../mock-server/MockServerPool";
import { ElevenLabsClient } from "../../../../src/Client";

describe("Members", () => {
    test("remove", async () => {
        const server = mockServerPool.createServer();
        const client = new ElevenLabsClient({
            apiKey: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl },
        });
        const rawRequestBody = { email: "email" };
        const rawResponseBody = { status: "ok" };
        server
            .mockEndpoint()
            .post("/v1/workspace/groups/group_id/members/remove")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.workspace.groups.members.remove("group_id", {
            email: "email",
        });
        expect(response).toEqual({
            status: "ok",
        });
    });

    test("add", async () => {
        const server = mockServerPool.createServer();
        const client = new ElevenLabsClient({
            apiKey: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl },
        });
        const rawRequestBody = { email: "email" };
        const rawResponseBody = { status: "ok" };
        server
            .mockEndpoint()
            .post("/v1/workspace/groups/group_id/members")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.workspace.groups.members.add("group_id", {
            email: "email",
        });
        expect(response).toEqual({
            status: "ok",
        });
    });
});
