// This file was auto-generated by Fern from our API Definition.

import { ElevenLabsClient } from "../../../../src/Client";
import { mockServerPool } from "../../../mock-server/MockServerPool";

describe("RunsClient", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new ElevenLabsClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            runs: [
                {
                    id: "sess_JWr5N6X9ZTqf8jD2LmQb",
                    template_id: "tmpl_abc123",
                    version_id: "ver_01hxyz",
                    status: "generating",
                    outputs: {
                        marketing_title: { type: "string", id: "JWr5N6X9ZTqf8jD2LmQb", status: "pending" },
                        product_demo: { type: "video", id: "JWr5N6X9ZTqf8jD2LmQb", status: "pending" },
                        product_still: { type: "image", id: "JWr5N6X9ZTqf8jD2LmQb", status: "pending" },
                    },
                },
            ],
            next_cursor: "MjAyNi0wNy0xN1QxMjowMDowMHxLeDJtUDdZNFdWcmc5a0UzTm5SYw",
            has_more: true,
        };

        server
            .mockEndpoint()
            .get("/v1/flows/templates/template_id/runs")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.flows.templates.runs.list("template_id", {
            cursor: "cursor",
            pageSize: 1,
            versionId: "version_id",
        });
        expect(response).toEqual({
            runs: [
                {
                    id: "sess_JWr5N6X9ZTqf8jD2LmQb",
                    templateId: "tmpl_abc123",
                    versionId: "ver_01hxyz",
                    status: "generating",
                    outputs: {
                        marketing_title: {
                            type: "string",
                            id: "JWr5N6X9ZTqf8jD2LmQb",
                            status: "pending",
                        },
                        product_demo: {
                            type: "video",
                            id: "JWr5N6X9ZTqf8jD2LmQb",
                            status: "pending",
                        },
                        product_still: {
                            type: "image",
                            id: "JWr5N6X9ZTqf8jD2LmQb",
                            status: "pending",
                        },
                    },
                },
            ],
            nextCursor: "MjAyNi0wNy0xN1QxMjowMDowMHxLeDJtUDdZNFdWcmc5a0UzTm5SYw",
            hasMore: true,
        });
    });

    test("create", async () => {
        const server = mockServerPool.createServer();
        const client = new ElevenLabsClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            inputs: {
                prompt: "a corgi on a surfboard",
                reference: { type: "asset", asset_id: "5xM2KqOnZyce22SPZ9d4" },
            },
            version_id: "latest",
            webhook: { type: "all" },
        };
        const rawResponseBody = {
            id: "sess_JWr5N6X9ZTqf8jD2LmQb",
            template_id: "tmpl_abc123",
            version_id: "ver_01hxyz",
            status: "generating",
            outputs: {
                marketing_title: {
                    type: "string",
                    id: "JWr5N6X9ZTqf8jD2LmQb",
                    status: "pending",
                    failure_reason: "timeout",
                    error_message: "error_message",
                    content: "content",
                },
                product_demo: {
                    type: "video",
                    id: "JWr5N6X9ZTqf8jD2LmQb",
                    status: "pending",
                    failure_reason: "timeout",
                    error_message: "error_message",
                    content_url: "content_url",
                    content_mime_type: "content_mime_type",
                },
                product_still: {
                    type: "image",
                    id: "JWr5N6X9ZTqf8jD2LmQb",
                    status: "pending",
                    failure_reason: "timeout",
                    error_message: "error_message",
                    content_url: "content_url",
                    content_mime_type: "content_mime_type",
                },
            },
        };

        server
            .mockEndpoint()
            .post("/v1/flows/templates/template_id/runs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.flows.templates.runs.create("template_id", {
            inputs: {
                prompt: "a corgi on a surfboard",
                reference: {
                    type: "asset",
                    assetId: "5xM2KqOnZyce22SPZ9d4",
                },
            },
            versionId: "latest",
            webhook: {
                type: "all",
            },
        });
        expect(response).toEqual({
            id: "sess_JWr5N6X9ZTqf8jD2LmQb",
            templateId: "tmpl_abc123",
            versionId: "ver_01hxyz",
            status: "generating",
            outputs: {
                marketing_title: {
                    type: "string",
                    id: "JWr5N6X9ZTqf8jD2LmQb",
                    status: "pending",
                    failureReason: "timeout",
                    errorMessage: "error_message",
                    content: "content",
                },
                product_demo: {
                    type: "video",
                    id: "JWr5N6X9ZTqf8jD2LmQb",
                    status: "pending",
                    failureReason: "timeout",
                    errorMessage: "error_message",
                    contentUrl: "content_url",
                    contentMimeType: "content_mime_type",
                },
                product_still: {
                    type: "image",
                    id: "JWr5N6X9ZTqf8jD2LmQb",
                    status: "pending",
                    failureReason: "timeout",
                    errorMessage: "error_message",
                    contentUrl: "content_url",
                    contentMimeType: "content_mime_type",
                },
            },
        });
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new ElevenLabsClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "sess_JWr5N6X9ZTqf8jD2LmQb",
            template_id: "tmpl_abc123",
            version_id: "ver_01hxyz",
            status: "generating",
            outputs: {
                marketing_title: {
                    type: "string",
                    id: "JWr5N6X9ZTqf8jD2LmQb",
                    status: "pending",
                    failure_reason: "timeout",
                    error_message: "error_message",
                    content: "content",
                },
                product_demo: {
                    type: "video",
                    id: "JWr5N6X9ZTqf8jD2LmQb",
                    status: "pending",
                    failure_reason: "timeout",
                    error_message: "error_message",
                    content_url: "content_url",
                    content_mime_type: "content_mime_type",
                },
                product_still: {
                    type: "image",
                    id: "JWr5N6X9ZTqf8jD2LmQb",
                    status: "pending",
                    failure_reason: "timeout",
                    error_message: "error_message",
                    content_url: "content_url",
                    content_mime_type: "content_mime_type",
                },
            },
        };

        server
            .mockEndpoint()
            .get("/v1/flows/templates/template_id/runs/run_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.flows.templates.runs.get("template_id", "run_id");
        expect(response).toEqual({
            id: "sess_JWr5N6X9ZTqf8jD2LmQb",
            templateId: "tmpl_abc123",
            versionId: "ver_01hxyz",
            status: "generating",
            outputs: {
                marketing_title: {
                    type: "string",
                    id: "JWr5N6X9ZTqf8jD2LmQb",
                    status: "pending",
                    failureReason: "timeout",
                    errorMessage: "error_message",
                    content: "content",
                },
                product_demo: {
                    type: "video",
                    id: "JWr5N6X9ZTqf8jD2LmQb",
                    status: "pending",
                    failureReason: "timeout",
                    errorMessage: "error_message",
                    contentUrl: "content_url",
                    contentMimeType: "content_mime_type",
                },
                product_still: {
                    type: "image",
                    id: "JWr5N6X9ZTqf8jD2LmQb",
                    status: "pending",
                    failureReason: "timeout",
                    errorMessage: "error_message",
                    contentUrl: "content_url",
                    contentMimeType: "content_mime_type",
                },
            },
        });
    });
});
