/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../../index";
import * as ElevenLabs from "../../../../../../../../../api/index";
import * as core from "../../../../../../../../../core";

export const BodyCreateChapterV1StudioProjectsProjectIdChaptersPost: core.serialization.Schema<
    serializers.studio.projects.BodyCreateChapterV1StudioProjectsProjectIdChaptersPost.Raw,
    ElevenLabs.studio.projects.BodyCreateChapterV1StudioProjectsProjectIdChaptersPost
> = core.serialization.object({
    name: core.serialization.string(),
    fromUrl: core.serialization.property("from_url", core.serialization.string().optional()),
});

export declare namespace BodyCreateChapterV1StudioProjectsProjectIdChaptersPost {
    export interface Raw {
        name: string;
        from_url?: string | null;
    }
}
