// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../../../../../../../../api/index";
import * as core from "../../../../../../../../../../../core";
import type * as serializers from "../../../../../../../../../../index";

export const DubbingTargetSegmentUpdateRequest: core.serialization.Schema<
    serializers.dubbing.project.language.DubbingTargetSegmentUpdateRequest.Raw,
    ElevenLabs.dubbing.project.language.DubbingTargetSegmentUpdateRequest
> = core.serialization.object({
    translation: core.serialization.string().optional(),
});

export declare namespace DubbingTargetSegmentUpdateRequest {
    export interface Raw {
        translation?: string | null;
    }
}
