// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { CompositionPlan } from "../../../types/CompositionPlan.js";
import { MusicPrompt } from "../../../types/MusicPrompt.js";

export const BodyComposeMusicV1MusicPostCompositionPlan: core.serialization.Schema<
    serializers.BodyComposeMusicV1MusicPostCompositionPlan.Raw,
    ElevenLabs.BodyComposeMusicV1MusicPostCompositionPlan
> = core.serialization.undiscriminatedUnion([MusicPrompt, CompositionPlan]);

export declare namespace BodyComposeMusicV1MusicPostCompositionPlan {
    export type Raw = MusicPrompt.Raw | CompositionPlan.Raw;
}
