// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const MusicSeparateStemsRequestStemVariationId: core.serialization.Schema<
    serializers.MusicSeparateStemsRequestStemVariationId.Raw,
    ElevenLabs.MusicSeparateStemsRequestStemVariationId
> = core.serialization.enum_(["two_stems_v1", "six_stems_v1"]);

export declare namespace MusicSeparateStemsRequestStemVariationId {
    export type Raw = "two_stems_v1" | "six_stems_v1";
}
