// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { DialogueInput } from "../../../../types/DialogueInput.js";
import { ModelSettingsResponseModel } from "../../../../types/ModelSettingsResponseModel.js";
import { PronunciationDictionaryVersionLocator } from "../../../../types/PronunciationDictionaryVersionLocator.js";
import { BodyTextToDialogueFullWithTimestampsApplyTextNormalization } from "../../types/BodyTextToDialogueFullWithTimestampsApplyTextNormalization.js";

export const BodyTextToDialogueFullWithTimestamps: core.serialization.Schema<
    serializers.BodyTextToDialogueFullWithTimestamps.Raw,
    Omit<ElevenLabs.BodyTextToDialogueFullWithTimestamps, "outputFormat" | "enableLogging">
> = core.serialization.object({
    inputs: core.serialization.list(DialogueInput),
    modelId: core.serialization.property("model_id", core.serialization.string().optional()),
    languageCode: core.serialization.property("language_code", core.serialization.string().optional()),
    settings: ModelSettingsResponseModel.optional(),
    pronunciationDictionaryLocators: core.serialization.property(
        "pronunciation_dictionary_locators",
        core.serialization.list(PronunciationDictionaryVersionLocator).optional(),
    ),
    seed: core.serialization.number().optional(),
    applyTextNormalization: core.serialization.property(
        "apply_text_normalization",
        BodyTextToDialogueFullWithTimestampsApplyTextNormalization.optional(),
    ),
});

export declare namespace BodyTextToDialogueFullWithTimestamps {
    export interface Raw {
        inputs: DialogueInput.Raw[];
        model_id?: string | null;
        language_code?: string | null;
        settings?: ModelSettingsResponseModel.Raw | null;
        pronunciation_dictionary_locators?: PronunciationDictionaryVersionLocator.Raw[] | null;
        seed?: number | null;
        apply_text_normalization?: BodyTextToDialogueFullWithTimestampsApplyTextNormalization.Raw | null;
    }
}
