// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../../api/index";
import * as core from "../../../../../core";
import type * as serializers from "../../../../index";
import { DialogueInput } from "../../../../types/DialogueInput";
import { ModelSettingsResponseModel } from "../../../../types/ModelSettingsResponseModel";
import { PronunciationDictionaryVersionLocator } from "../../../../types/PronunciationDictionaryVersionLocator";
import { BodyTextToDialogueStreamWithTimestampsApplyTextNormalization } from "../../types/BodyTextToDialogueStreamWithTimestampsApplyTextNormalization";

export const BodyTextToDialogueStreamWithTimestamps: core.serialization.Schema<
    serializers.BodyTextToDialogueStreamWithTimestamps.Raw,
    Omit<ElevenLabs.BodyTextToDialogueStreamWithTimestamps, "outputFormat">
> = core.serialization.object({
    inputs: core.serialization.list(DialogueInput),
    modelId: core.serialization.property("model_id", core.serialization.string().optional()),
    languageCode: core.serialization.property("language_code", core.serialization.string().optional()),
    settings: ModelSettingsResponseModel.optional(),
    pronunciationDictionaryLocators: core.serialization.property(
        "pronunciation_dictionary_locators",
        core.serialization.list(PronunciationDictionaryVersionLocator).optional(),
    ),
    seed: core.serialization.number().optional(),
    applyTextNormalization: core.serialization.property(
        "apply_text_normalization",
        BodyTextToDialogueStreamWithTimestampsApplyTextNormalization.optional(),
    ),
});

export declare namespace BodyTextToDialogueStreamWithTimestamps {
    export interface Raw {
        inputs: DialogueInput.Raw[];
        model_id?: string | null;
        language_code?: string | null;
        settings?: ModelSettingsResponseModel.Raw | null;
        pronunciation_dictionary_locators?: PronunciationDictionaryVersionLocator.Raw[] | null;
        seed?: number | null;
        apply_text_normalization?: BodyTextToDialogueStreamWithTimestampsApplyTextNormalization.Raw | null;
    }
}
