// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../../../../index.js";

export type UpdateDocumentsResponse =
    | ElevenLabs.agents.knowledgeBase.UpdateDocumentsResponse.Url
    | ElevenLabs.agents.knowledgeBase.UpdateDocumentsResponse.File
    | ElevenLabs.agents.knowledgeBase.UpdateDocumentsResponse.Text
    | ElevenLabs.agents.knowledgeBase.UpdateDocumentsResponse.Folder;

export namespace UpdateDocumentsResponse {
    export interface Url extends ElevenLabs.GetKnowledgeBaseUrlResponseModel {
        type: "url";
    }

    export interface File extends ElevenLabs.GetKnowledgeBaseFileResponseModel {
        type: "file";
    }

    export interface Text extends ElevenLabs.GetKnowledgeBaseTextResponseModel {
        type: "text";
    }

    export interface Folder extends ElevenLabs.GetKnowledgeBaseFolderResponseModel {
        type: "folder";
    }
}
