// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const AudioIsolationRequestFileFormat: core.serialization.Schema<
    serializers.AudioIsolationRequestFileFormat.Raw,
    ElevenLabs.AudioIsolationRequestFileFormat
> = core.serialization.enum_(["pcm_s16le_16", "other"]);

export declare namespace AudioIsolationRequestFileFormat {
    export type Raw = "pcm_s16le_16" | "other";
}
