// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../../../../api/index.js";
import * as core from "../../../../../../../core/index.js";
import type * as serializers from "../../../../../../index.js";

export const RemovePronunciationDictionaryRulesRequest: core.serialization.Schema<
    serializers.pronunciationDictionaries.RemovePronunciationDictionaryRulesRequest.Raw,
    ElevenLabs.pronunciationDictionaries.RemovePronunciationDictionaryRulesRequest
> = core.serialization.object({
    ruleStrings: core.serialization.property("rule_strings", core.serialization.list(core.serialization.string())),
});

export declare namespace RemovePronunciationDictionaryRulesRequest {
    export interface Raw {
        rule_strings: string[];
    }
}
