// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../../../../../api/index.js";
import * as core from "../../../../../../../../core/index.js";
import type * as serializers from "../../../../../../../index.js";
import { BatchFailureResponseModel } from "../../../../../../../types/BatchFailureResponseModel.js";
import { KnowledgeBaseBulkDeleteSuccessfulResponseModel } from "../../../../../../../types/KnowledgeBaseBulkDeleteSuccessfulResponseModel.js";

export const BulkDeleteDocumentsResponseValue: core.serialization.Schema<
    serializers.agents.knowledgeBase.BulkDeleteDocumentsResponseValue.Raw,
    ElevenLabs.agents.knowledgeBase.BulkDeleteDocumentsResponseValue
> = core.serialization
    .union("status", {
        success: KnowledgeBaseBulkDeleteSuccessfulResponseModel,
        failure: BatchFailureResponseModel,
    })
    .transform<ElevenLabs.agents.knowledgeBase.BulkDeleteDocumentsResponseValue>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace BulkDeleteDocumentsResponseValue {
    export type Raw = BulkDeleteDocumentsResponseValue.Success | BulkDeleteDocumentsResponseValue.Failure;

    export interface Success extends KnowledgeBaseBulkDeleteSuccessfulResponseModel.Raw {
        status: "success";
    }

    export interface Failure extends BatchFailureResponseModel.Raw {
        status: "failure";
    }
}
