// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { RttEndOfStreamPayload } from "../../../types/RttEndOfStreamPayload";
import { RttInputAudioChunkPayload } from "../../../types/RttInputAudioChunkPayload";

export const SendRttMessage: core.serialization.Schema<serializers.SendRttMessage.Raw, ElevenLabs.SendRttMessage> =
    core.serialization.undiscriminatedUnion([RttInputAudioChunkPayload, RttEndOfStreamPayload]);

export declare namespace SendRttMessage {
    export type Raw = RttInputAudioChunkPayload.Raw | RttEndOfStreamPayload.Raw;
}
