/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePost {
    /** The name of the pronunciation dictionary, used for identification only. */
    name: string;
    /** A description of the pronunciation dictionary, used for identification only. */
    description: string;
}
