// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient";
import { AnalyticsClient } from "../resources/analytics/client/Client";
import { AuditLogsClient } from "../resources/auditLogs/client/Client";
import { AuthConnectionsClient } from "../resources/authConnections/client/Client";
import { GroupsClient } from "../resources/groups/client/Client";
import { InvitesClient } from "../resources/invites/client/Client";
import { MembersClient } from "../resources/members/client/Client";
import { ResourcesClient } from "../resources/resources/client/Client";
import { UsageClient } from "../resources/usage/client/Client";

export declare namespace WorkspaceClient {
    export type Options = BaseClientOptions;
}

export class WorkspaceClient {
    protected readonly _options: NormalizedClientOptions<WorkspaceClient.Options>;
    protected _auditLogs: AuditLogsClient | undefined;
    protected _authConnections: AuthConnectionsClient | undefined;
    protected _groups: GroupsClient | undefined;
    protected _invites: InvitesClient | undefined;
    protected _members: MembersClient | undefined;
    protected _resources: ResourcesClient | undefined;
    protected _usage: UsageClient | undefined;
    protected _analytics: AnalyticsClient | undefined;

    constructor(options: WorkspaceClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    public get auditLogs(): AuditLogsClient {
        return (this._auditLogs ??= new AuditLogsClient(this._options));
    }

    public get authConnections(): AuthConnectionsClient {
        return (this._authConnections ??= new AuthConnectionsClient(this._options));
    }

    public get groups(): GroupsClient {
        return (this._groups ??= new GroupsClient(this._options));
    }

    public get invites(): InvitesClient {
        return (this._invites ??= new InvitesClient(this._options));
    }

    public get members(): MembersClient {
        return (this._members ??= new MembersClient(this._options));
    }

    public get resources(): ResourcesClient {
        return (this._resources ??= new ResourcesClient(this._options));
    }

    public get usage(): UsageClient {
        return (this._usage ??= new UsageClient(this._options));
    }

    public get analytics(): AnalyticsClient {
        return (this._analytics ??= new AnalyticsClient(this._options));
    }
}
