export { BodyCopyWorkspaceResourceToAnotherWorkspaceV1WorkspaceResourcesResourceIdCopyToWorkspacePost } from "./BodyCopyWorkspaceResourceToAnotherWorkspaceV1WorkspaceResourcesResourceIdCopyToWorkspacePost";
export { BodyShareWorkspaceResourceV1WorkspaceResourcesResourceIdSharePost } from "./BodyShareWorkspaceResourceV1WorkspaceResourcesResourceIdSharePost";
export { BodyUnshareWorkspaceResourceV1WorkspaceResourcesResourceIdUnsharePost } from "./BodyUnshareWorkspaceResourceV1WorkspaceResourcesResourceIdUnsharePost";
