// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

export interface AgentMergeProposalResponse {
    id: string;
    agentId: string;
    sourceBranchId: string;
    targetBranchId: string;
    sourceTipVersionIdAtCreation: string;
    title: string;
    description?: string;
    requestedReviewerUserIds?: string[];
    reviews?: ElevenLabs.MergeProposalReview[];
    comments?: ElevenLabs.MergeProposalComment[];
    outcome?: ElevenLabs.AgentMergeProposalResponseOutcome;
    createdAt: number;
    updatedAt: number;
    /** User ID of the merge_proposal's author. */
    authorUserId?: string;
    /** Access information for the merge_proposal, including creator. */
    accessInfo?: ElevenLabs.ResourceAccessInfo;
}
