// This file was auto-generated by Fern from our API Definition.

export const AgentDeploymentSource = {
    Manual: "manual",
    BranchMerge: "branch_merge",
} as const;
export type AgentDeploymentSource = (typeof AgentDeploymentSource)[keyof typeof AgentDeploymentSource];
