// This file was auto-generated by Fern from our API Definition.

export interface AlertingWebhookNotifier {
    type?: "webhook";
    /** The URL to send alert lifecycle notifications to. */
    url: string;
}
