// This file was auto-generated by Fern from our API Definition.

export interface ArchitectDispatchResponseModel {
    architectChatId: string;
    userId: string;
    dispatchedAtUnixSecs: number;
}
