// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

/**
 * Expression selected if the condition is true.
 */
export type AstConditionalOperatorNodeInputTrueExpression =
    | ElevenLabs.AstConditionalOperatorNodeInputTrueExpression.AndOperator
    | ElevenLabs.AstConditionalOperatorNodeInputTrueExpression.BooleanLiteral
    | ElevenLabs.AstConditionalOperatorNodeInputTrueExpression.ConditionalOperator
    | ElevenLabs.AstConditionalOperatorNodeInputTrueExpression.DynamicVariable
    | ElevenLabs.AstConditionalOperatorNodeInputTrueExpression.EqOperator
    | ElevenLabs.AstConditionalOperatorNodeInputTrueExpression.GtOperator
    | ElevenLabs.AstConditionalOperatorNodeInputTrueExpression.GteOperator
    | ElevenLabs.AstConditionalOperatorNodeInputTrueExpression.Llm
    | ElevenLabs.AstConditionalOperatorNodeInputTrueExpression.LtOperator
    | ElevenLabs.AstConditionalOperatorNodeInputTrueExpression.LteOperator
    | ElevenLabs.AstConditionalOperatorNodeInputTrueExpression.NeqOperator
    | ElevenLabs.AstConditionalOperatorNodeInputTrueExpression.NumberLiteral
    | ElevenLabs.AstConditionalOperatorNodeInputTrueExpression.OrOperator
    | ElevenLabs.AstConditionalOperatorNodeInputTrueExpression.StringLiteral;

export namespace AstConditionalOperatorNodeInputTrueExpression {
    export interface AndOperator extends ElevenLabs.AstAndOperatorNodeInput {
        type: "and_operator";
    }

    export interface BooleanLiteral extends ElevenLabs.AstBooleanNodeInput {
        type: "boolean_literal";
    }

    export interface ConditionalOperator extends ElevenLabs.AstConditionalOperatorNodeInput {
        type: "conditional_operator";
    }

    export interface DynamicVariable extends ElevenLabs.AstDynamicVariableNodeInput {
        type: "dynamic_variable";
    }

    export interface EqOperator extends ElevenLabs.AstEqualsOperatorNodeInput {
        type: "eq_operator";
    }

    export interface GtOperator extends ElevenLabs.AstGreaterThanOperatorNodeInput {
        type: "gt_operator";
    }

    export interface GteOperator extends ElevenLabs.AstGreaterThanOrEqualsOperatorNodeInput {
        type: "gte_operator";
    }

    export interface Llm {
        type: "llm";
        value: ElevenLabs.AstllmNodeInput;
    }

    export interface LtOperator extends ElevenLabs.AstLessThanOperatorNodeInput {
        type: "lt_operator";
    }

    export interface LteOperator extends ElevenLabs.AstLessThanOrEqualsOperatorNodeInput {
        type: "lte_operator";
    }

    export interface NeqOperator extends ElevenLabs.AstNotEqualsOperatorNodeInput {
        type: "neq_operator";
    }

    export interface NumberLiteral extends ElevenLabs.AstNumberNodeInput {
        type: "number_literal";
    }

    export interface OrOperator extends ElevenLabs.AstOrOperatorNodeInput {
        type: "or_operator";
    }

    export interface StringLiteral extends ElevenLabs.AstStringNodeInput {
        type: "string_literal";
    }
}
