// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

export interface AstOrOperatorNodeInput {
    /** Child nodes of the logical operator. */
    children: ElevenLabs.AstOrOperatorNodeInputChildrenItem[];
}
