/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Current state of the project
 */
export type AudioNativeProjectSettingsResponseModelStatus = "processing" | "ready";
export const AudioNativeProjectSettingsResponseModelStatus = {
    Processing: "processing",
    Ready: "ready",
} as const;
