// This file was auto-generated by Fern from our API Definition.

/** Current state of the project */
export const AudioNativeProjectSettingsResponseModelStatus = {
    Processing: "processing",
    Ready: "ready",
} as const;
export type AudioNativeProjectSettingsResponseModelStatus =
    (typeof AudioNativeProjectSettingsResponseModelStatus)[keyof typeof AudioNativeProjectSettingsResponseModelStatus];
