// This file was auto-generated by Fern from our API Definition.

export interface AvatarContextRequestModel {
    avatarId?: string;
    avatarStyleId?: string;
    avatarName?: string;
    avatarStyleName?: string;
}
