/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumeration.
 */
export type BanReasonType = "safety" | "manual";
export const BanReasonType = {
    Safety: "safety",
    Manual: "manual",
} as const;
