// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

export interface BatchCallResponse {
    id: string;
    phoneNumberId?: string;
    phoneProvider?: ElevenLabs.TelephonyProvider;
    whatsappParams?: ElevenLabs.BatchCallWhatsAppParams;
    name: string;
    agentId: string;
    createdAtUnix: number;
    scheduledTimeUnix: number;
    totalCallsDispatched: number;
    totalCallsScheduled: number;
    totalCallsFinished: number;
    lastUpdatedAtUnix: number;
    status: ElevenLabs.BatchCallStatus;
    retryCount: number;
    agentName: string;
}
