// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

/**
 * Response model for bearer auth
 */
export interface BearerAuthResponse {
    name: string;
    provider: string;
    id: string;
    usedBy?: ElevenLabs.AuthConnectionDependencies;
}
