// This file was auto-generated by Fern from our API Definition.

export interface BodyTranscribesSegmentsV1DubbingResourceDubbingIdTranscribePost {
    /** Transcribe this specific list of segments. */
    segments: string[];
}
