/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type BodyAddProjectV1ProjectsAddPostSourceType = "blank" | "book" | "article" | "genfm";
export const BodyAddProjectV1ProjectsAddPostSourceType = {
    Blank: "blank",
    Book: "book",
    Article: "article",
    Genfm: "genfm",
} as const;
