/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElevenLabs from "../index";

/**
 * The source content for the Podcast.
 */
export type BodyCreatePodcastV1ProjectsPodcastCreatePostSource =
    | ElevenLabs.PodcastTextSource
    | ElevenLabs.PodcastUrlSource
    | ElevenLabs.BodyCreatePodcastV1ProjectsPodcastCreatePostSourceItem[];
