/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CaptionStyleCharacterAnimationModelExitType = "none" | "fade";
export const CaptionStyleCharacterAnimationModelExitType = {
    None: "none",
    Fade: "fade",
} as const;
