/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The state of the chapter.
 */
export type ChapterWithContentResponseModelState = "default" | "converting";
export const ChapterWithContentResponseModelState = {
    Default: "default",
    Converting: "converting",
} as const;
