// This file was auto-generated by Fern from our API Definition.

export const ChatSourceMedium = {
    Audio: "audio",
    Dtmf: "dtmf",
    Text: "text",
    Image: "image",
    File: "file",
} as const;
export type ChatSourceMedium = (typeof ChatSourceMedium)[keyof typeof ChatSourceMedium];
