// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

/**
 * Payload for committed transcription results with word-level timestamps.
 */
export interface CommittedTranscriptWithTimestampsPayload {
    /** The message type identifier. */
    messageType: "committed_transcript_with_timestamps";
    /** Committed transcription text. */
    text: string;
    /** Detected or specified language code. */
    languageCode?: string;
    /** Word-level information with timestamps. */
    words?: ElevenLabs.TranscriptionWord[];
}
