// This file was auto-generated by Fern from our API Definition.

import * as ElevenLabs from "../index";

export interface ConversationHistoryAnalysisCommonModel {
    evaluationCriteriaResults?: Record<string, ElevenLabs.ConversationHistoryEvaluationCriteriaResultCommonModel>;
    dataCollectionResults?: Record<string, ElevenLabs.DataCollectionResultCommonModel>;
    callSuccessful: ElevenLabs.EvaluationSuccessResult;
    transcriptSummary: string;
    callSummaryTitle?: string;
}
