// This file was auto-generated by Fern from our API Definition.

/** Stored in conversation history. Never exposed to customers directly. */
export const ConversationErrorType = {
    Unknown: "unknown",
    CallInitializationError: "call_initialization_error",
    LineBusy: "line_busy",
    NoAnswer: "no_answer",
    CallRejected: "call_rejected",
    BlockedByUser: "blocked_by_user",
    AgentConfigurationError: "agent_configuration_error",
    InvalidClientRequest: "invalid_client_request",
    PermissionError: "permission_error",
    EntitlementExceeded: "entitlement_exceeded",
    ClientDisconnected: "client_disconnected",
    LlmError: "llm_error",
    SpeechError: "speech_error",
    ToolError: "tool_error",
    IntegrationError: "integration_error",
    DependencyError: "dependency_error",
    GuardrailTriggered: "guardrail_triggered",
    SafetyViolation: "safety_violation",
    MaxDurationExceeded: "max_duration_exceeded",
    InternalError: "internal_error",
    PostProcessingError: "post_processing_error",
} as const;
export type ConversationErrorType = (typeof ConversationErrorType)[keyof typeof ConversationErrorType];
