// This file was auto-generated by Fern from our API Definition.

export interface ConversationUserResponseModel {
    userId: string;
    lastContactUnixSecs: number;
    firstContactUnixSecs: number;
    conversationCount: number;
    lastAgentId?: string;
    lastAgentName?: string;
}
