// This file was auto-generated by Fern from our API Definition.

import * as ElevenLabs from "../index";

export interface ConversationHistoryTranscriptWorkflowToolsResultCommonModelOutput {
    requestId: string;
    toolName: string;
    resultValue: string;
    isError: boolean;
    toolHasBeenCalled: boolean;
    toolLatencySecs?: number;
    dynamicVariableUpdates?: ElevenLabs.DynamicVariableUpdateCommonModel[];
    type: "workflow";
    result?: ElevenLabs.WorkflowToolResponseModelOutput;
}
