/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateTwilioPhoneNumberRequest {
    /** Phone number */
    phone_number: string;
    /** Label for the phone number */
    label: string;
    /** Twilio Account SID */
    sid: string;
    /** Twilio Auth Token */
    token: string;
}
