// This file was auto-generated by Fern from our API Definition.

export interface CreateAgentBranchResponseModel {
    /** ID of the created branch */
    createdBranchId: string;
    /** ID of the first version on the created branch */
    createdVersionId: string;
}
