// This file was auto-generated by Fern from our API Definition.

export interface CreateOrderRequest {
    /** When true, creates a sandbox order that auto-progresses without producer intervention. */
    sandbox?: boolean;
}
