// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

/**
 * Config container for custom guardrails list
 */
export interface CustomGuardrailsConfigInput {
    configs?: ElevenLabs.CustomGuardrailConfig[];
}
