// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

export interface DubbingProjectListResponse {
    /** The page of dubbing projects the caller can access. */
    projects: ElevenLabs.DubbingProjectResponse[];
    /** Cursor for the next page, or null when there are no more results. */
    nextCursor?: string;
}
