// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index.js";

export interface DubbingTranscriptWord {
    text?: string;
    wordType?: string;
    startS?: number;
    endS?: number;
    characters?: ElevenLabs.DubbingTranscriptCharacter[];
}
