// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

export interface DubbingStatus {
    messageType: "status";
    status: ElevenLabs.DubbingStatusStatus;
}
