// This file was auto-generated by Fern from our API Definition.

/** Lifecycle status: 'queued' (waiting on the project), 'processing', 'completed', 'stale' (source/transcript changed), or 'failed'. */
export const DubbingLanguageResponseStatus = {
    Queued: "queued",
    Processing: "processing",
    Completed: "completed",
    Stale: "stale",
    Failed: "failed",
} as const;
export type DubbingLanguageResponseStatus =
    (typeof DubbingLanguageResponseStatus)[keyof typeof DubbingLanguageResponseStatus];
