// This file was auto-generated by Fern from our API Definition.

export interface DuplicateSpeechEngineRequest {
    /** Name for the duplicated speech engine. Defaults to the source name. */
    name?: string;
}
