// This file was auto-generated by Fern from our API Definition.

import * as ElevenLabs from "../index";

export interface DynamicVariablesConfig {
    /** A dictionary of dynamic variable placeholders and their values */
    dynamicVariablePlaceholders?: Record<string, ElevenLabs.DynamicVariablesConfigDynamicVariablePlaceholdersValue>;
}
