// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

/**
 * The pending change for the user.
 */
export type ExtendedSubscriptionResponseModelPendingChange =
    | ElevenLabs.PendingSubscriptionSwitchResponseModel
    | ElevenLabs.PendingCancellationResponseModel;
