/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ExtendedSubscriptionResponseModelBillingPeriod = "monthly_period" | "annual_period";

export const ExtendedSubscriptionResponseModelBillingPeriod = {
    MonthlyPeriod: "monthly_period",
    AnnualPeriod: "annual_period",
} as const;
