/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElevenLabs from "../index";

export interface GetAgentLinkResponseModel {
    agent_id: string;
    token?: ElevenLabs.ConversationTokenDbModel;
}
