// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

export interface GetConversationResponseModel {
    agentId: string;
    agentName?: string;
    status: ElevenLabs.GetConversationResponseModelStatus;
    userId?: string;
    branchId?: string;
    /** The ID of the agent version used for this conversation */
    versionId?: string;
    metadata: ElevenLabs.ConversationHistoryMetadataCommonModel;
    analysis?: ElevenLabs.ConversationHistoryAnalysisCommonModel;
    visitedAgents?: ElevenLabs.VisitedAgentRef[];
    conversationInitiationClientData?: ElevenLabs.ConversationInitiationClientDataRequestOutput;
    environment?: string;
    conversationId: string;
    hasAudio: boolean;
    hasUserAudio: boolean;
    hasResponseAudio: boolean;
    transcript: ElevenLabs.ConversationHistoryTranscriptResponseModel[];
}
