// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

export interface GetKnowledgeBaseSummaryTextResponseModel {
    id: string;
    name: string;
    metadata: ElevenLabs.KnowledgeBaseDocumentMetadataResponseModel;
    supportedUsages: ElevenLabs.DocumentUsageModeEnum[];
    accessInfo: ElevenLabs.ResourceAccessInfo;
    dependentAgents: ElevenLabs.GetKnowledgeBaseSummaryTextResponseModelDependentAgentsItem[];
}
