// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

export type GetSecretDependenciesResponseModelDependenciesZeroItem =
    | ElevenLabs.GetSecretDependenciesResponseModelDependenciesZeroItem.Available
    | ElevenLabs.GetSecretDependenciesResponseModelDependenciesZeroItem.Unknown;

export namespace GetSecretDependenciesResponseModelDependenciesZeroItem {
    export interface Available extends ElevenLabs.DependentAvailableToolIdentifier {
        type: "available";
    }

    export interface Unknown extends ElevenLabs.DependentUnknownToolIdentifier {
        type: "unknown";
    }
}
