// This file was auto-generated by Fern from our API Definition.

/** The quality of the output image. */
export const GptImage25SunburstRequestQuality = {
    Low: "low",
    Medium: "medium",
    High: "high",
    Xhigh: "xhigh",
    Max: "max",
} as const;
export type GptImage25SunburstRequestQuality =
    (typeof GptImage25SunburstRequestQuality)[keyof typeof GptImage25SunburstRequestQuality];
