// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

export interface GuardrailsV1Output {
    version?: "1";
    alignment?: ElevenLabs.AlignmentGuardrail;
    content?: ElevenLabs.ContentGuardrailOutput;
    moderation?: ElevenLabs.ModerationGuardrailOutput;
    custom?: ElevenLabs.CustomGuardrailOutput;
}
