/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface HistoryAlignmentResponseModel {
    /** The characters in the alignment. */
    characters: string[];
    /** The start times of the characters in seconds. */
    character_start_times_seconds: number[];
    /** The end times of the characters in seconds. */
    character_end_times_seconds: number[];
}
