/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElevenLabs from "../index";

export interface InitializeConnection {
    /** The initial text that must be sent is a blank space. */
    text: " ";
    voice_settings?: ElevenLabs.RealtimeVoiceSettings;
    generation_config?: ElevenLabs.GenerationConfig;
    /**
     * Optional list of pronunciation dictionary locators. If provided, these dictionaries will be used to
     * modify pronunciation of matching text. Must only be provided in the first message.
     *
     * Note: Pronunciation dictionary matches will only be respected within a provided chunk.
     */
    pronunciation_dictionary_locators?: ElevenLabs.PronunciationDictionaryLocator[];
    /** Your ElevenLabs API key. This can only be included in the first message and is not needed if present in the header. */
    "xi-api-key"?: string;
    /** Your authorization bearer token. This can only be included in the first message and is not needed if present in the header. */
    authorization?: string;
}
