// This file was auto-generated by Fern from our API Definition.

export interface InitializeConnectionMultiPronunciationDictionaryLocatorsItem {
    pronunciationDictionaryId: string;
    versionId: string;
}
