// This file was auto-generated by Fern from our API Definition.

/** The MIME type of the encoded video. */
export const InlineVideoReferenceMimeType = {
    VideoMp4: "video/mp4",
    VideoQuicktime: "video/quicktime",
    VideoWebm: "video/webm",
} as const;
export type InlineVideoReferenceMimeType =
    (typeof InlineVideoReferenceMimeType)[keyof typeof InlineVideoReferenceMimeType];
