// This file was auto-generated by Fern from our API Definition.

export interface KeepContextAlive {
    /** An empty string. Ignored by the server but resets the inactivity timeout for the context. */
    text: "";
    contextId: string;
}
