/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface LanguageResponse {
    /** The unique identifier of the language. */
    language_id: string;
    /** The name of the language. */
    name: string;
}
