// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

/**
 * Derived approval state for a currently discovered MCP tool.
 */
export interface McpToolApprovalStatus {
    /** Canonical MCP tool identifier in the form mcp:<server_id>:<tool_name> */
    toolId: string;
    /** Whether a stored approval exists and still matches the live tool definition */
    state: ElevenLabs.McpToolApprovalState;
    /** Stored execution policy. Set when the tool has an approval. */
    approvalPolicy?: ElevenLabs.McpToolApprovalPolicy;
    /** Previously approved definition, included when the tool needs review and a snapshot exists. */
    approvedDefinition?: ElevenLabs.McpApprovedToolDefinition;
}
