// This file was auto-generated by Fern from our API Definition.

export const MergeProposalReviewState = {
    Approved: "approved",
    ChangesRequested: "changes_requested",
} as const;
export type MergeProposalReviewState = (typeof MergeProposalReviewState)[keyof typeof MergeProposalReviewState];
