// This file was auto-generated by Fern from our API Definition.

export const MergeProposalCloseReason = {
    Withdrawn: "withdrawn",
    Rejected: "rejected",
    BranchArchived: "branch_archived",
} as const;
export type MergeProposalCloseReason = (typeof MergeProposalCloseReason)[keyof typeof MergeProposalCloseReason];
