// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

/**
 * JSON-serializable multi-source retrieval configuration.
 *
 * This can be passed as JSON in tool configurations for full control.
 */
export interface MultiSourceConfigJson {
    /** List of source names to use (e.g., ['chunks', 'products']) */
    sourceNames?: string[];
    /** Per-source parameter overrides */
    sourceOverrides?: ElevenLabs.SourceConfigJson[];
    /** How to merge results from multiple sources */
    mergingStrategy?: ElevenLabs.MergingStrategy;
    /** Final number of chunks after merging */
    finalTopK?: number;
    /** Decompose complex queries */
    useDecomposition?: boolean;
    /** LLM reformulates query */
    useReformulation?: boolean;
    /** LLM generates answer vs raw chunks */
    synthesizeResponse?: boolean;
}
