// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

export interface MusicFinetunePageResponseModel {
    /** The finetunes in this page. */
    finetunes: ElevenLabs.MusicFinetuneResponseModel[];
    /** Cursor to pass as `cursor` to fetch the next page; `null` when there are no more results. */
    nextCursor?: string;
    /** Whether more finetunes are available beyond this page. */
    hasMore: boolean;
}
