// This file was auto-generated by Fern from our API Definition.

export const MusicOnlyOutputFormats = {
    Mp348000128: "mp3_48000_128",
    Mp348000192: "mp3_48000_192",
    Mp348000240: "mp3_48000_240",
    Mp348000320: "mp3_48000_320",
} as const;
export type MusicOnlyOutputFormats = (typeof MusicOnlyOutputFormats)[keyof typeof MusicOnlyOutputFormats];
