// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

export interface ObjectSchema {
    title?: string;
    description?: string;
    properties?: Record<string, ElevenLabs.ContentSchema>;
    required?: string[];
}
