// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

export interface PhoneNumberTransfer {
    transferDestination?: ElevenLabs.PhoneNumberTransferTransferDestination;
    phoneNumber?: string;
    condition: string;
    transferType?: ElevenLabs.TransferTypeEnum;
}
