// This file was auto-generated by Fern from our API Definition.

export interface PodcastUrlSource {
    /** The type of source to create. */
    type: "url";
    /** The URL to create the podcast from. */
    url: string;
}
