// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

export interface ProcedureListItemResponseModel {
    /** Procedure ID */
    procedureId: string;
    /** Version ID of a version of the procedure. None for a procedure never versioned. */
    versionId?: string;
    /** Procedure name */
    name?: string;
    /** Procedure type */
    type?: ElevenLabs.ProcedureType;
    /** When the agent should use this procedure. Empty string means this is a sub-procedure that should only start when another procedure references it. */
    trigger?: string;
    /** True when the procedure has unpublished draft changes on this branch (a newly created or edited procedure not yet published). When true, the name, type, and trigger reflect that draft. */
    hasDraft: boolean;
}
