/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElevenLabs from "../index";

/**
 * The type of tool
 */
export type PromptAgentApiModelWorkflowOverrideToolsItem =
    | ElevenLabs.PromptAgentApiModelWorkflowOverrideToolsItem.Client
    | ElevenLabs.PromptAgentApiModelWorkflowOverrideToolsItem.Mcp
    | ElevenLabs.PromptAgentApiModelWorkflowOverrideToolsItem.System
    | ElevenLabs.PromptAgentApiModelWorkflowOverrideToolsItem.Webhook;

export namespace PromptAgentApiModelWorkflowOverrideToolsItem {
    export interface Client extends ElevenLabs.ClientToolConfigInput {
        type: "client";
    }

    export interface Mcp {
        type: "mcp";
        value?: unknown;
    }

    export interface System extends ElevenLabs.SystemToolConfigInput {
        type: "system";
    }

    export interface Webhook extends ElevenLabs.WebhookToolConfigInput {
        type: "webhook";
    }
}
