// This file was auto-generated by Fern from our API Definition.

import * as ElevenLabs from "../index";

/**
 * The type of tool
 */
export type PromptAgentApiModelWorkflowOverrideInputToolsItem =
    | ElevenLabs.PromptAgentApiModelWorkflowOverrideInputToolsItem.Client
    | ElevenLabs.PromptAgentApiModelWorkflowOverrideInputToolsItem.Mcp
    | ElevenLabs.PromptAgentApiModelWorkflowOverrideInputToolsItem.System
    | ElevenLabs.PromptAgentApiModelWorkflowOverrideInputToolsItem.Webhook;

export namespace PromptAgentApiModelWorkflowOverrideInputToolsItem {
    export interface Client extends ElevenLabs.ClientToolConfigInput {
        type: "client";
    }

    export interface Mcp {
        type: "mcp";
        value?: unknown;
    }

    export interface System extends ElevenLabs.SystemToolConfigInput {
        type: "system";
    }

    export interface Webhook extends ElevenLabs.WebhookToolConfigInput {
        type: "webhook";
    }
}
