// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

export interface RealtimeConfigSnapshot {
    id: string;
    workspaceId: string;
    conversationId: string;
    seqNo: number;
    timeInCallSecs: number;
    timeCommittedSecs: number;
    sourceEventId?: number;
    parents: ElevenLabs.RealtimeConfigSnapshotParents;
    sessionConfig: ElevenLabs.OpenAiSessionConfig;
    safety: ElevenLabs.SafetyCommonModelOutput;
    changedPaths?: string[];
}
