/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElevenLabs from "../index";

export interface ShareOptionResponseModel {
    /** The name of the principal. */
    name: string;
    /** The ID of the principal. */
    id: string;
    /** The type of the principal: user, group, or service account (under 'key'). */
    type: ElevenLabs.ShareOptionResponseModelType;
}
