// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

export interface SpeechEngineResponse {
    /** The speech engine resource ID */
    speechEngineId: string;
    name: string;
    speechEngine: ElevenLabs.SpeechEngineConfig;
    asr: ElevenLabs.AsrConversationalConfig;
    tts: ElevenLabs.TtsConversationalConfigOutput;
    turn: ElevenLabs.BaseTurnConfig;
    conversation: ElevenLabs.ConversationConfigOutput;
    privacy: ElevenLabs.PrivacyConfigOutput;
    callLimits: ElevenLabs.AgentCallLimits;
    language: string;
    tags: string[];
    metadata: ElevenLabs.AgentMetadataDbModel;
}
