/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SpeechHistoryItemResponseModelVoiceCategory = "premade" | "cloned" | "generated" | "professional";
export const SpeechHistoryItemResponseModelVoiceCategory = {
    Premade: "premade",
    Cloned: "cloned",
    Generated: "generated",
    Professional: "professional",
} as const;
