// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

/**
 * An `object` output, delivered as `content` once completed: one output per
 * field of the schema's `properties`, each an output in its own right with
 * its own `status`. There are no dynamic fields.
 */
export interface TemplateObjectOutput {
    /** The id of the generation behind this output. Pass it as a `generation` reference to use the output as an input elsewhere. */
    id: string;
    /** The lifecycle status of the output. It ends at `completed`, when the output's content fields are set, or `failed`, when `failure_reason` and `error_message` are set. */
    status: ElevenLabs.TemplateRunStatus;
    /** The category of failure. Present only when `status` is `failed`. */
    failureReason?: ElevenLabs.TemplateObjectOutputFailureReason;
    /** A human-readable description of the failure. Present only when `status` is `failed`. Failed generations are not charged. */
    errorMessage?: string;
    /** One output per field, keyed by field name, each following the shape of that field's schema. Present only when `status` is `completed`. Reserved: no template produces this kind of output yet; it is published so that templates which do can be run with the same client. */
    content?: Record<string, ElevenLabs.TemplateOutput | undefined>;
}
