// This file was auto-generated by Fern from our API Definition.

export interface TextToDialogueWebsocketFinalAudioForTurnMulti {
    /** Indicates that the final audio for a given turn of this context has been sent. */
    isFinalAudioForTurn?: boolean;
    /** The context whose turn has finished. */
    contextId?: string;
}
