// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index.js";

export interface ToolRequestModel {
    /** Configuration for the tool */
    toolConfig: ElevenLabs.ToolRequestModelToolConfig;
    /** Mock responses with optional parameter conditions. Evaluated top-to-bottom; first match wins. */
    responseMocks?: ElevenLabs.ToolResponseMockConfigInput[];
}
