// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

export interface ToolResponseMockConfigOutput {
    /** If the list is empty, the mock will always activate. */
    parameterConditions?: ElevenLabs.UnitTestToolCallParameter[];
    /** The return value the LLM sees when this mock is active. */
    mockResult: string;
}
