// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

export interface TranscriptionOrderItemRequest {
    /** The IDs of the uploaded media files to transcribe. */
    mediaIds: ElevenLabs.MediaId[];
    /** The language code of the source media (e.g. 'en', 'es'). */
    sourceLanguage: string;
    /** Whether to transcribe every word exactly, including filler words. */
    verbatim?: boolean;
    /** Optional free-text instructions for the transcription team. */
    instructions?: string;
}
