// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

/**
 * A single turn in the conversation history.
 */
export interface TranscriptMessage {
    /** The speaker for this turn. */
    role: ElevenLabs.TranscriptMessageRole;
    /** The transcript text for this turn. */
    content: string;
}
