// This file was auto-generated by Fern from our API Definition.

/** Version of the turn detection model to use. */
export const TurnModel = {
    TurnV2: "turn_v2",
    TurnV3: "turn_v3",
} as const;
export type TurnModel = (typeof TurnModel)[keyof typeof TurnModel];
