// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

export interface UnitTestRunResponseModel {
    testRunId: string;
    testInfo?: ElevenLabs.UnitTestRunResponseModelTestInfo;
    testInvocationId: string;
    agentId: string;
    branchId?: string;
    workflowNodeId?: string;
    status: ElevenLabs.TestRunStatus;
    agentResponses?: ElevenLabs.ConversationHistoryTranscriptCommonModelOutput[];
    testId: string;
    testName?: string;
    conditionResult?: ElevenLabs.TestConditionResultCommonModel;
    lastUpdatedAtUnix?: number;
    metadata?: ElevenLabs.TestRunMetadata;
}
