// This file was auto-generated by Fern from our API Definition.

export const UsersSortBy = {
    LastContactUnixSecs: "last_contact_unix_secs",
    ConversationCount: "conversation_count",
} as const;
export type UsersSortBy = (typeof UsersSortBy)[keyof typeof UsersSortBy];
