/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface VoiceSampleVisualWaveformResponseModel {
    /** The ID of the sample. */
    sampleId: string;
    /** The visual waveform of the sample, represented as a list of floats. */
    visualWaveform: number[];
}
