/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The review status of the voice.
 */
export type VoiceSharingResponseModelReviewStatus =
    | "not_requested"
    | "pending"
    | "declined"
    | "allowed"
    | "allowed_with_changes";
export const VoiceSharingResponseModelReviewStatus = {
    NotRequested: "not_requested",
    Pending: "pending",
    Declined: "declined",
    Allowed: "allowed",
    AllowedWithChanges: "allowed_with_changes",
} as const;
