// This file was auto-generated by Fern from our API Definition.

/**
 * Deliver the result to specific configured flows webhooks.
 */
export interface WebhookTargetIds {
    /** The IDs of the workspace flows webhooks to deliver the result to. Each must be one of the workspace's configured flows webhooks. */
    ids: string[];
}
