/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElevenLabs from "../index";

export interface WidgetConfigResponseModel {
    variant?: ElevenLabs.EmbedVariant;
    avatar?: ElevenLabs.WidgetConfigResponseModelAvatar;
    feedback_mode?: ElevenLabs.WidgetFeedbackMode;
    bg_color?: string;
    text_color?: string;
    btn_color?: string;
    btn_text_color?: string;
    border_color?: string;
    focus_color?: string;
    border_radius?: number;
    btn_radius?: number;
    action_text?: string;
    start_call_text?: string;
    end_call_text?: string;
    expand_text?: string;
    listening_text?: string;
    speaking_text?: string;
    shareable_page_text?: string;
    terms_text?: string;
    terms_html?: string;
    terms_key?: string;
    language: string;
    supported_language_overrides?: string[];
}
