// This file was auto-generated by Fern from our API Definition.

import * as ElevenLabs from "../index";

export interface WidgetLanguagePreset {
    /** The text contents for the selected language */
    textContents?: ElevenLabs.WidgetTextContents;
}
