// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

export interface WorkflowToolNestedToolsStepModelOutput {
    stepLatencySecs: number;
    nodeId: string;
    requests: ElevenLabs.ConversationHistoryTranscriptToolCallCommonModel[];
    results: ElevenLabs.WorkflowToolNestedToolsStepModelOutputResultsItem[];
    isSuccessful: boolean;
}
