// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../index";

export type WorkflowToolResponseModelInputStepsItem =
    | ElevenLabs.WorkflowToolResponseModelInputStepsItem.Edge
    | ElevenLabs.WorkflowToolResponseModelInputStepsItem.MaxIterationsExceeded
    | ElevenLabs.WorkflowToolResponseModelInputStepsItem.NestedTools;

export namespace WorkflowToolResponseModelInputStepsItem {
    export interface Edge extends ElevenLabs.WorkflowToolEdgeStepModel {
        type: "edge";
    }

    export interface MaxIterationsExceeded extends ElevenLabs.WorkflowToolMaxIterationsExceededStepModel {
        type: "max_iterations_exceeded";
    }

    export interface NestedTools extends ElevenLabs.WorkflowToolNestedToolsStepModelInput {
        type: "nested_tools";
    }
}
