// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { AudioChunkMulti } from "../../../types/AudioChunkMulti";
import { Error_ } from "../../../types/Error_";
import { FinalAudioForTurnMulti } from "../../../types/FinalAudioForTurnMulti";
import { FinalMulti } from "../../../types/FinalMulti";

export const ReceiveTextToDialogueWebsocketMessageMulti: core.serialization.Schema<
    serializers.ReceiveTextToDialogueWebsocketMessageMulti.Raw,
    ElevenLabs.ReceiveTextToDialogueWebsocketMessageMulti
> = core.serialization.undiscriminatedUnion([AudioChunkMulti, FinalAudioForTurnMulti, FinalMulti, Error_]);

export declare namespace ReceiveTextToDialogueWebsocketMessageMulti {
    export type Raw = AudioChunkMulti.Raw | FinalAudioForTurnMulti.Raw | FinalMulti.Raw | Error_.Raw;
}
