/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElevenLabs from "../../../../../../index";

/**
 * @example
 *     {
 *         isEnabled: true,
 *         name: "Sneaky Fox",
 *         permissions: ["text_to_speech"]
 *     }
 */
export interface BodyEditServiceAccountApiKeyV1ServiceAccountsServiceAccountUserIdApiKeysApiKeyIdPatch {
    /** Whether to enable or disable the API key. */
    isEnabled: boolean;
    /** The name of the XI API key to use (used for identification purposes only). */
    name: string;
    /** The permissions of the XI API. */
    permissions: ElevenLabs.serviceAccounts.BodyEditServiceAccountApiKeyV1ServiceAccountsServiceAccountUserIdApiKeysApiKeyIdPatchPermissions;
    /** The character limit of the XI API key. If provided this will limit the usage of this api key to n characters per month where n is the chosen value. Requests that incur charges will fail after reaching this monthly limit. */
    characterLimit?: number;
}
