// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import type * as serializers from "../../../../../../index";

export const BodyDeleteExistingInvitationV1WorkspaceInvitesDelete: core.serialization.Schema<
    serializers.workspace.BodyDeleteExistingInvitationV1WorkspaceInvitesDelete.Raw,
    ElevenLabs.workspace.BodyDeleteExistingInvitationV1WorkspaceInvitesDelete
> = core.serialization.object({
    email: core.serialization.string(),
});

export declare namespace BodyDeleteExistingInvitationV1WorkspaceInvitesDelete {
    export interface Raw {
        email: string;
    }
}
