// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import type * as serializers from "../../../../../index.js";

export const ListConversationsRequestSummaryMode: core.serialization.Schema<
    serializers.agents.ListConversationsRequestSummaryMode.Raw,
    ElevenLabs.agents.ListConversationsRequestSummaryMode
> = core.serialization.enum_(["exclude", "include"]);

export declare namespace ListConversationsRequestSummaryMode {
    export type Raw = "exclude" | "include";
}
