// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../index";

export type BodyComposeMusicWithADetailedResponseV1MusicDetailedPostCompositionPlan =
    | ElevenLabs.MusicPrompt
    | ElevenLabs.CompositionPlan;
