/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as fs from "fs";

/**
 * @example
 *     {
 *         target_lang: "target_lang"
 *     }
 */
export interface BodyDubAVideoOrAnAudioFileV1DubbingPost {
    file?: File | fs.ReadStream,
    csvFile?: File | fs.ReadStream,
    foregroundAudioFile?: File | fs.ReadStream,
    backgroundAudioFile?: File | fs.ReadStream,
    /** automatic or manual. */
    mode?: string;
    /** Name of the dubbing project. */
    name?: string;
    /** URL of the source video/audio file. */
    source_url?: string;
    /** Source language. */
    source_lang?: string;
    /** The Target language to dub the content into. Can be none if dubbing studio editor is enabled and running manual mode */
    target_lang: string;
    /** Number of speakers to use for the dubbing. */
    num_speakers?: number;
    /** Whether to apply watermark to the output video. */
    watermark?: boolean;
    /** Start time of the source video/audio file. */
    start_time?: number;
    /** End time of the source video/audio file. */
    end_time?: number;
    /** Whether to use the highest resolution available. */
    highest_resolution?: boolean;
    /** Whether to prepare dub for edits in dubbing studio. */
    dubbing_studio?: boolean;
}
