/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElevenLabs from "../../../../index";

/**
 * @example
 *     {}
 */
export interface DubbingGetTranscriptForDubRequest {
    /**
     * Format to use for the subtitle file, either 'srt' or 'webvtt'
     */
    format_type?: ElevenLabs.DubbingGetTranscriptForDubRequestFormatType;
}
