// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface BodyEditPvcVoiceV1VoicesPvcVoiceIdPost {
    /** The name that identifies this voice. This will be displayed in the dropdown of the website. */
    name?: string;
    /** Language used in the samples. */
    language?: string;
    /** Description to use for the created voice. */
    description?: string;
    /** Serialized labels dictionary for the voice. */
    labels?: Record<string, string | undefined>;
}
