// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { CreateAuthConnectionEnvironmentVariableRequest } from "../../../types/CreateAuthConnectionEnvironmentVariableRequest.js";
import { CreateSecretEnvironmentVariableRequest } from "../../../types/CreateSecretEnvironmentVariableRequest.js";
import { CreateStringEnvironmentVariableRequest } from "../../../types/CreateStringEnvironmentVariableRequest.js";

export const CreateEnvironmentVariablesRequestBody: core.serialization.Schema<
    serializers.CreateEnvironmentVariablesRequestBody.Raw,
    ElevenLabs.CreateEnvironmentVariablesRequestBody
> = core.serialization
    .union("type", {
        string: CreateStringEnvironmentVariableRequest,
        secret: CreateSecretEnvironmentVariableRequest,
        auth_connection: CreateAuthConnectionEnvironmentVariableRequest,
    })
    .transform<ElevenLabs.CreateEnvironmentVariablesRequestBody>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace CreateEnvironmentVariablesRequestBody {
    export type Raw =
        | CreateEnvironmentVariablesRequestBody.String
        | CreateEnvironmentVariablesRequestBody.Secret
        | CreateEnvironmentVariablesRequestBody.AuthConnection;

    export interface String extends CreateStringEnvironmentVariableRequest.Raw {
        type: "string";
    }

    export interface Secret extends CreateSecretEnvironmentVariableRequest.Raw {
        type: "secret";
    }

    export interface AuthConnection extends CreateAuthConnectionEnvironmentVariableRequest.Raw {
        type: "auth_connection";
    }
}
