// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../../../../index";

export type DocumentsBulkDeleteResponseValue =
    | ElevenLabs.conversationalAi.knowledgeBase.DocumentsBulkDeleteResponseValue.Success
    | ElevenLabs.conversationalAi.knowledgeBase.DocumentsBulkDeleteResponseValue.Failure;

export namespace DocumentsBulkDeleteResponseValue {
    export interface Success extends ElevenLabs.KnowledgeBaseBulkDeleteSuccessfulResponseModel {
        status: "success";
    }

    export interface Failure extends ElevenLabs.BatchFailureResponseModel {
        status: "failure";
    }
}
