/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../../../../mock-server/MockServerPool.js";
import { ElevenLabsClient } from "../../../../../src/Client";

describe("Audio", () => {
    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new ElevenLabsClient({
            apiKey: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl },
        });

        const rawResponseBody = {
            audio_base_64: "audio_base_64",
            voice_id: "DCwhRBWXzGAHq8TQ4Fs18",
            sample_id: "DCwhRBWXzGAHq8TQ4Fs18",
            media_type: "audio/mpeg",
            duration_secs: 5,
        };
        server
            .mockEndpoint()
            .get("/v1/voices/pvc/21m00Tcm4TlvDq8ikWAM/samples/VW7YKqPnjY4h39yTbx2L/audio")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.voices.pvc.samples.audio.get("21m00Tcm4TlvDq8ikWAM", "VW7YKqPnjY4h39yTbx2L");
        expect(response).toEqual({
            audioBase64: "audio_base_64",
            voiceId: "DCwhRBWXzGAHq8TQ4Fs18",
            sampleId: "DCwhRBWXzGAHq8TQ4Fs18",
            mediaType: "audio/mpeg",
            durationSecs: 5,
        });
    });
});
