// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { TranslateAudio } from "../../../types/TranslateAudio.js";
import { TranslateAudioOutputError } from "../../../types/TranslateAudioOutputError.js";
import { TranslateAuthError } from "../../../types/TranslateAuthError.js";
import { TranslateError } from "../../../types/TranslateError.js";
import { TranslateFinalTranscript } from "../../../types/TranslateFinalTranscript.js";
import { TranslateInputError } from "../../../types/TranslateInputError.js";
import { TranslatePartialTranscript } from "../../../types/TranslatePartialTranscript.js";
import { TranslateQueueOverflowError } from "../../../types/TranslateQueueOverflowError.js";
import { TranslateRateLimitedError } from "../../../types/TranslateRateLimitedError.js";
import { TranslateSessionStarted } from "../../../types/TranslateSessionStarted.js";
import { TranslateStatus } from "../../../types/TranslateStatus.js";
import { TranslateTranscriberError } from "../../../types/TranslateTranscriberError.js";
import { TranslateTranslation } from "../../../types/TranslateTranslation.js";
import { TranslateTranslationError } from "../../../types/TranslateTranslationError.js";

export const ReceiveTranslateStreamMessage: core.serialization.Schema<
    serializers.ReceiveTranslateStreamMessage.Raw,
    ElevenLabs.ReceiveTranslateStreamMessage
> = core.serialization.undiscriminatedUnion([
    TranslateSessionStarted,
    TranslateStatus,
    TranslatePartialTranscript,
    TranslateFinalTranscript,
    TranslateTranslation,
    TranslateAudio,
    TranslateError,
    TranslateAuthError,
    TranslateRateLimitedError,
    TranslateQueueOverflowError,
    TranslateInputError,
    TranslateTranscriberError,
    TranslateTranslationError,
    TranslateAudioOutputError,
]);

export declare namespace ReceiveTranslateStreamMessage {
    export type Raw =
        | TranslateSessionStarted.Raw
        | TranslateStatus.Raw
        | TranslatePartialTranscript.Raw
        | TranslateFinalTranscript.Raw
        | TranslateTranslation.Raw
        | TranslateAudio.Raw
        | TranslateError.Raw
        | TranslateAuthError.Raw
        | TranslateRateLimitedError.Raw
        | TranslateQueueOverflowError.Raw
        | TranslateInputError.Raw
        | TranslateTranscriberError.Raw
        | TranslateTranslationError.Raw
        | TranslateAudioOutputError.Raw;
}
