// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         branchId: "agtbrch_8901k4t9z5defmb8vh3e9361y7nj"
 *     }
 */
export interface DraftsDeleteRequest {
    /** The ID of the agent branch to use */
    branchId: string;
}
