// This file was auto-generated by Fern from our API Definition.

import * as ElevenLabs from "../../../../../../../../index";

/**
 * @example
 *     {
 *         testRunIds: ["test_run_ids"],
 *         agentId: "agent_id"
 *     }
 */
export interface ResubmitTestsRequestModel {
    /** List of test run IDs to resubmit */
    testRunIds: string[];
    /** Configuration overrides to use for testing. If not provided, the agent's default configuration will be used. */
    agentConfigOverride?: ElevenLabs.AdhocAgentConfigOverrideForTestRequestModel;
    /** Agent ID to resubmit tests for */
    agentId: string;
}
