export { BodyCreateAgentTestFolderV1ConvaiAgentTestingFoldersPost } from "./BodyCreateAgentTestFolderV1ConvaiAgentTestingFoldersPost.js";
export { BodyUpdateAgentTestFolderV1ConvaiAgentTestingFoldersFolderIdPatch } from "./BodyUpdateAgentTestFolderV1ConvaiAgentTestingFoldersFolderIdPatch.js";
