// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AddWorkspaceInviteResponseModel: core.serialization.ObjectSchema<
    serializers.AddWorkspaceInviteResponseModel.Raw,
    ElevenLabs.AddWorkspaceInviteResponseModel
> = core.serialization.object({
    status: core.serialization.string(),
});

export declare namespace AddWorkspaceInviteResponseModel {
    export interface Raw {
        status: string;
    }
}
