// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { AgentDeploymentSource } from "./AgentDeploymentSource";
import { ResourceAccessInfo } from "./ResourceAccessInfo";

export const AgentDeploymentHistoryItem: core.serialization.ObjectSchema<
    serializers.AgentDeploymentHistoryItem.Raw,
    ElevenLabs.AgentDeploymentHistoryItem
> = core.serialization.object({
    id: core.serialization.string(),
    trafficPercentageBranchIdMap: core.serialization.property(
        "traffic_percentage_branch_id_map",
        core.serialization.record(core.serialization.string(), core.serialization.number()).optional(),
    ),
    deployedAtUnixSecs: core.serialization.property("deployed_at_unix_secs", core.serialization.number()),
    isActive: core.serialization.property("is_active", core.serialization.boolean()),
    source: AgentDeploymentSource.optional(),
    accessInfo: core.serialization.property("access_info", ResourceAccessInfo.optional()),
});

export declare namespace AgentDeploymentHistoryItem {
    export interface Raw {
        id: string;
        traffic_percentage_branch_id_map?: Record<string, number> | null;
        deployed_at_unix_secs: number;
        is_active: boolean;
        source?: AgentDeploymentSource.Raw | null;
        access_info?: ResourceAccessInfo.Raw | null;
    }
}
