// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { DynamicVariablesConfigWorkflowOverride } from "./DynamicVariablesConfigWorkflowOverride";
import { PromptAgentApiModelWorkflowOverrideOutput } from "./PromptAgentApiModelWorkflowOverrideOutput";

export const AgentConfigApiModelWorkflowOverrideOutput: core.serialization.ObjectSchema<
    serializers.AgentConfigApiModelWorkflowOverrideOutput.Raw,
    ElevenLabs.AgentConfigApiModelWorkflowOverrideOutput
> = core.serialization.object({
    firstMessage: core.serialization.property("first_message", core.serialization.string().optional()),
    language: core.serialization.string().optional(),
    hinglishMode: core.serialization.property("hinglish_mode", core.serialization.boolean().optional()),
    dynamicVariables: core.serialization.property(
        "dynamic_variables",
        DynamicVariablesConfigWorkflowOverride.optional(),
    ),
    disableFirstMessageInterruptions: core.serialization.property(
        "disable_first_message_interruptions",
        core.serialization.boolean().optional(),
    ),
    prompt: PromptAgentApiModelWorkflowOverrideOutput.optional(),
});

export declare namespace AgentConfigApiModelWorkflowOverrideOutput {
    export interface Raw {
        first_message?: string | null;
        language?: string | null;
        hinglish_mode?: boolean | null;
        dynamic_variables?: DynamicVariablesConfigWorkflowOverride.Raw | null;
        disable_first_message_interruptions?: boolean | null;
        prompt?: PromptAgentApiModelWorkflowOverrideOutput.Raw | null;
    }
}
