// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const AlertingSlackNotifierResponse: core.serialization.ObjectSchema<
    serializers.AlertingSlackNotifierResponse.Raw,
    ElevenLabs.AlertingSlackNotifierResponse
> = core.serialization.object({
    type: core.serialization.stringLiteral("integration").optional(),
    integrationType: core.serialization.property(
        "integration_type",
        core.serialization.stringLiteral("slack").optional(),
    ),
    connectionId: core.serialization.property("connection_id", core.serialization.string()),
    channelId: core.serialization.property("channel_id", core.serialization.string()),
});

export declare namespace AlertingSlackNotifierResponse {
    export interface Raw {
        type?: "integration" | null;
        integration_type?: "slack" | null;
        connection_id: string;
        channel_id: string;
    }
}
