// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { ConstantSchemaOverride } from "./ConstantSchemaOverride";
import { DynamicVariableSchemaOverride } from "./DynamicVariableSchemaOverride";
import { LlmSchemaOverride } from "./LlmSchemaOverride";

export const ApiIntegrationWebhookOverridesSchemaOverridesValue: core.serialization.Schema<
    serializers.ApiIntegrationWebhookOverridesSchemaOverridesValue.Raw,
    ElevenLabs.ApiIntegrationWebhookOverridesSchemaOverridesValue
> = core.serialization
    .union("source", {
        constant: ConstantSchemaOverride,
        dynamic_variable: DynamicVariableSchemaOverride,
        llm: LlmSchemaOverride,
    })
    .transform<ElevenLabs.ApiIntegrationWebhookOverridesSchemaOverridesValue>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace ApiIntegrationWebhookOverridesSchemaOverridesValue {
    export type Raw =
        | ApiIntegrationWebhookOverridesSchemaOverridesValue.Constant
        | ApiIntegrationWebhookOverridesSchemaOverridesValue.DynamicVariable
        | ApiIntegrationWebhookOverridesSchemaOverridesValue.Llm;

    export interface Constant extends ConstantSchemaOverride.Raw {
        source: "constant";
    }

    export interface DynamicVariable extends DynamicVariableSchemaOverride.Raw {
        source: "dynamic_variable";
    }

    export interface Llm extends LlmSchemaOverride.Raw {
        source: "llm";
    }
}
