// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import * as serializers from "../index";

export const AstAdditionOperatorNodeInput: core.serialization.ObjectSchema<
    serializers.AstAdditionOperatorNodeInput.Raw,
    ElevenLabs.AstAdditionOperatorNodeInput
> = core.serialization.object({
    left: core.serialization.lazy(() => serializers.AstAdditionOperatorNodeInputLeft),
    right: core.serialization.lazy(() => serializers.AstAdditionOperatorNodeInputRight),
});

export declare namespace AstAdditionOperatorNodeInput {
    export interface Raw {
        left: serializers.AstAdditionOperatorNodeInputLeft.Raw;
        right: serializers.AstAdditionOperatorNodeInputRight.Raw;
    }
}
