// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const AstDynamicVariableNodeOutput: core.serialization.ObjectSchema<
    serializers.AstDynamicVariableNodeOutput.Raw,
    ElevenLabs.AstDynamicVariableNodeOutput
> = core.serialization.object({
    name: core.serialization.string(),
});

export declare namespace AstDynamicVariableNodeOutput {
    export interface Raw {
        name: string;
    }
}
