// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { LlmLiteralJsonSchemaProperty } from "./LlmLiteralJsonSchemaProperty.js";

export const AstllmNodeOutput: core.serialization.ObjectSchema<
    serializers.AstllmNodeOutput.Raw,
    ElevenLabs.AstllmNodeOutput
> = core.serialization.object({
    valueSchema: core.serialization.property("value_schema", LlmLiteralJsonSchemaProperty),
    prompt: core.serialization.string(),
});

export declare namespace AstllmNodeOutput {
    export interface Raw {
        value_schema: LlmLiteralJsonSchemaProperty.Raw;
        prompt: string;
    }
}
