// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import * as serializers from "../index";

export const AstMultiplicationOperatorNodeOutput: core.serialization.ObjectSchema<
    serializers.AstMultiplicationOperatorNodeOutput.Raw,
    ElevenLabs.AstMultiplicationOperatorNodeOutput
> = core.serialization.object({
    left: core.serialization.lazy(() => serializers.AstMultiplicationOperatorNodeOutputLeft),
    right: core.serialization.lazy(() => serializers.AstMultiplicationOperatorNodeOutputRight),
});

export declare namespace AstMultiplicationOperatorNodeOutput {
    export interface Raw {
        left: serializers.AstMultiplicationOperatorNodeOutputLeft.Raw;
        right: serializers.AstMultiplicationOperatorNodeOutputRight.Raw;
    }
}
