// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import * as serializers from "../index";

export const AstOrOperatorNodeOutput: core.serialization.ObjectSchema<
    serializers.AstOrOperatorNodeOutput.Raw,
    ElevenLabs.AstOrOperatorNodeOutput
> = core.serialization.object({
    children: core.serialization.list(core.serialization.lazy(() => serializers.AstOrOperatorNodeOutputChildrenItem)),
});

export declare namespace AstOrOperatorNodeOutput {
    export interface Raw {
        children: serializers.AstOrOperatorNodeOutputChildrenItem.Raw[];
    }
}
