// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const AudioNativeProjectSettingsResponseModelStatus: core.serialization.Schema<
    serializers.AudioNativeProjectSettingsResponseModelStatus.Raw,
    ElevenLabs.AudioNativeProjectSettingsResponseModelStatus
> = core.serialization.enum_(["processing", "ready"]);

export declare namespace AudioNativeProjectSettingsResponseModelStatus {
    export type Raw = "processing" | "ready";
}
