// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { AudioOutputMultiAlignment } from "./AudioOutputMultiAlignment";
import { AudioOutputMultiNormalizedAlignment } from "./AudioOutputMultiNormalizedAlignment";

export const AudioOutputMulti: core.serialization.ObjectSchema<
    serializers.AudioOutputMulti.Raw,
    ElevenLabs.AudioOutputMulti
> = core.serialization.object({
    audio: core.serialization.string(),
    isFinal: core.serialization.property("is_final", core.serialization.boolean().optional()),
    normalizedAlignment: core.serialization.property(
        "normalized_alignment",
        AudioOutputMultiNormalizedAlignment.optional(),
    ),
    alignment: AudioOutputMultiAlignment.optional(),
    contextId: core.serialization.property("context_id", core.serialization.string().optional()),
});

export declare namespace AudioOutputMulti {
    export interface Raw {
        audio: string;
        is_final?: boolean | null;
        normalized_alignment?: AudioOutputMultiNormalizedAlignment.Raw | null;
        alignment?: AudioOutputMultiAlignment.Raw | null;
        context_id?: string | null;
    }
}
