// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const AudioIsolationHistoryItemResponseModel: core.serialization.ObjectSchema<
    serializers.AudioIsolationHistoryItemResponseModel.Raw,
    ElevenLabs.AudioIsolationHistoryItemResponseModel
> = core.serialization.object({
    id: core.serialization.string(),
    title: core.serialization.string().optional(),
    createdAtUnix: core.serialization.property("created_at_unix", core.serialization.number()),
    format: core.serialization.string(),
    durationSeconds: core.serialization.property("duration_seconds", core.serialization.number().optional()),
    downloadUrl: core.serialization.property("download_url", core.serialization.string().optional()),
    iconUrl: core.serialization.property("icon_url", core.serialization.string().optional()),
    sourceVideoUrl: core.serialization.property("source_video_url", core.serialization.string().optional()),
    supportsVideo: core.serialization.property("supports_video", core.serialization.boolean()),
    processing: core.serialization.boolean(),
    previewB64: core.serialization.property("preview_b64", core.serialization.string().optional()),
});

export declare namespace AudioIsolationHistoryItemResponseModel {
    export interface Raw {
        id: string;
        title?: string | null;
        created_at_unix: number;
        format: string;
        duration_seconds?: number | null;
        download_url?: string | null;
        icon_url?: string | null;
        source_video_url?: string | null;
        supports_video: boolean;
        processing: boolean;
        preview_b64?: string | null;
    }
}
