// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { Llm } from "./Llm";

export const BackupLlmOverride: core.serialization.ObjectSchema<
    serializers.BackupLlmOverride.Raw,
    ElevenLabs.BackupLlmOverride
> = core.serialization.object({
    preference: core.serialization.stringLiteral("override").optional(),
    order: core.serialization.list(Llm),
});

export declare namespace BackupLlmOverride {
    export interface Raw {
        preference?: "override" | null;
        order: Llm.Raw[];
    }
}
