// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const BackupLlmDisabled: core.serialization.ObjectSchema<
    serializers.BackupLlmDisabled.Raw,
    ElevenLabs.BackupLlmDisabled
> = core.serialization.object({
    preference: core.serialization.stringLiteral("disabled").optional(),
});

export declare namespace BackupLlmDisabled {
    export interface Raw {
        preference?: "disabled" | null;
    }
}
