// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const BackupLlmDefault: core.serialization.ObjectSchema<
    serializers.BackupLlmDefault.Raw,
    ElevenLabs.BackupLlmDefault
> = core.serialization.object({});

export declare namespace BackupLlmDefault {
    export type Raw = {};
}
