// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const BadRequestErrorBody: core.serialization.ObjectSchema<
    serializers.BadRequestErrorBody.Raw,
    ElevenLabs.BadRequestErrorBody
> = core.serialization.object({
    error: core.serialization.string().optional(),
    message: core.serialization.string().optional(),
});

export declare namespace BadRequestErrorBody {
    export interface Raw {
        error?: string | null;
        message?: string | null;
    }
}
