// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const BatchFailureResponseModel: core.serialization.ObjectSchema<
    serializers.BatchFailureResponseModel.Raw,
    ElevenLabs.BatchFailureResponseModel
> = core.serialization.object({
    errorCode: core.serialization.property("error_code", core.serialization.number()),
    errorStatus: core.serialization.property("error_status", core.serialization.string()),
    errorMessage: core.serialization.property("error_message", core.serialization.string()),
});

export declare namespace BatchFailureResponseModel {
    export interface Raw {
        error_code: number;
        error_status: string;
        error_message: string;
    }
}
