/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import { TelephonyProvider } from "./TelephonyProvider";
import { BatchCallStatus } from "./BatchCallStatus";

export const BatchCallResponse: core.serialization.ObjectSchema<
    serializers.BatchCallResponse.Raw,
    ElevenLabs.BatchCallResponse
> = core.serialization.object({
    id: core.serialization.string(),
    phoneNumberId: core.serialization.property("phone_number_id", core.serialization.string()),
    phoneProvider: core.serialization.property("phone_provider", TelephonyProvider.optional()),
    name: core.serialization.string(),
    agentId: core.serialization.property("agent_id", core.serialization.string()),
    createdAtUnix: core.serialization.property("created_at_unix", core.serialization.number()),
    scheduledTimeUnix: core.serialization.property("scheduled_time_unix", core.serialization.number()),
    totalCallsDispatched: core.serialization.property("total_calls_dispatched", core.serialization.number()),
    totalCallsScheduled: core.serialization.property("total_calls_scheduled", core.serialization.number()),
    lastUpdatedAtUnix: core.serialization.property("last_updated_at_unix", core.serialization.number()),
    status: BatchCallStatus,
    agentName: core.serialization.property("agent_name", core.serialization.string()),
});

export declare namespace BatchCallResponse {
    export interface Raw {
        id: string;
        phone_number_id: string;
        phone_provider?: TelephonyProvider.Raw | null;
        name: string;
        agent_id: string;
        created_at_unix: number;
        scheduled_time_unix: number;
        total_calls_dispatched: number;
        total_calls_scheduled: number;
        last_updated_at_unix: number;
        status: BatchCallStatus.Raw;
        agent_name: string;
    }
}
