// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const BatchCallWhatsAppParams: core.serialization.ObjectSchema<
    serializers.BatchCallWhatsAppParams.Raw,
    ElevenLabs.BatchCallWhatsAppParams
> = core.serialization.object({
    whatsappBusinessAccountId: core.serialization.property("whatsapp_business_account_id", core.serialization.string()),
    whatsappCallPermissionRequestTemplateName: core.serialization.property(
        "whatsapp_call_permission_request_template_name",
        core.serialization.string(),
    ),
    whatsappCallPermissionRequestTemplateLanguageCode: core.serialization.property(
        "whatsapp_call_permission_request_template_language_code",
        core.serialization.string(),
    ),
});

export declare namespace BatchCallWhatsAppParams {
    export interface Raw {
        whatsapp_business_account_id: string;
        whatsapp_call_permission_request_template_name: string;
        whatsapp_call_permission_request_template_language_code: string;
    }
}
