// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { InteractionBudget } from "./InteractionBudget.js";
import { OutputFormat } from "./OutputFormat.js";
import { Verbosity } from "./Verbosity.js";

export const BehaviorOverride: core.serialization.ObjectSchema<
    serializers.BehaviorOverride.Raw,
    ElevenLabs.BehaviorOverride
> = core.serialization.object({
    verbosity: Verbosity.optional(),
    outputFormat: core.serialization.property("output_format", OutputFormat.optional()),
    interactionBudget: core.serialization.property("interaction_budget", InteractionBudget.optional()),
});

export declare namespace BehaviorOverride {
    export interface Raw {
        verbosity?: Verbosity.Raw | null;
        output_format?: OutputFormat.Raw | null;
        interaction_budget?: InteractionBudget.Raw | null;
    }
}
