/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";

export const BodyAddProjectV1ProjectsAddPostApplyTextNormalization: core.serialization.Schema<
    serializers.BodyAddProjectV1ProjectsAddPostApplyTextNormalization.Raw,
    ElevenLabs.BodyAddProjectV1ProjectsAddPostApplyTextNormalization
> = core.serialization.enum_(["auto", "on", "off", "apply_english"]);

export declare namespace BodyAddProjectV1ProjectsAddPostApplyTextNormalization {
    export type Raw = "auto" | "on" | "off" | "apply_english";
}
