/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import { PodcastTextSource } from "./PodcastTextSource";
import { PodcastUrlSource } from "./PodcastUrlSource";
import { BodyCreatePodcastV1ProjectsPodcastCreatePostSourceItem } from "./BodyCreatePodcastV1ProjectsPodcastCreatePostSourceItem";

export const BodyCreatePodcastV1ProjectsPodcastCreatePostSource: core.serialization.Schema<
    serializers.BodyCreatePodcastV1ProjectsPodcastCreatePostSource.Raw,
    ElevenLabs.BodyCreatePodcastV1ProjectsPodcastCreatePostSource
> = core.serialization.undiscriminatedUnion([
    PodcastTextSource,
    PodcastUrlSource,
    core.serialization.list(BodyCreatePodcastV1ProjectsPodcastCreatePostSourceItem),
]);

export declare namespace BodyCreatePodcastV1ProjectsPodcastCreatePostSource {
    export type Raw =
        | PodcastTextSource.Raw
        | PodcastUrlSource.Raw
        | BodyCreatePodcastV1ProjectsPodcastCreatePostSourceItem.Raw[];
}
