// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import { SystemToolConfigInput } from "./SystemToolConfigInput";

export const BuiltInToolsWorkflowOverride: core.serialization.ObjectSchema<
    serializers.BuiltInToolsWorkflowOverride.Raw,
    ElevenLabs.BuiltInToolsWorkflowOverride
> = core.serialization.object({
    endCall: core.serialization.property("end_call", SystemToolConfigInput.optional()),
    languageDetection: core.serialization.property("language_detection", SystemToolConfigInput.optional()),
    transferToAgent: core.serialization.property("transfer_to_agent", SystemToolConfigInput.optional()),
    transferToNumber: core.serialization.property("transfer_to_number", SystemToolConfigInput.optional()),
    skipTurn: core.serialization.property("skip_turn", SystemToolConfigInput.optional()),
    playKeypadTouchTone: core.serialization.property("play_keypad_touch_tone", SystemToolConfigInput.optional()),
    voicemailDetection: core.serialization.property("voicemail_detection", SystemToolConfigInput.optional()),
});

export declare namespace BuiltInToolsWorkflowOverride {
    export interface Raw {
        end_call?: SystemToolConfigInput.Raw | null;
        language_detection?: SystemToolConfigInput.Raw | null;
        transfer_to_agent?: SystemToolConfigInput.Raw | null;
        transfer_to_number?: SystemToolConfigInput.Raw | null;
        skip_turn?: SystemToolConfigInput.Raw | null;
        play_keypad_touch_tone?: SystemToolConfigInput.Raw | null;
        voicemail_detection?: SystemToolConfigInput.Raw | null;
    }
}
