// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { AudioReference } from "./AudioReference";
import { BytedanceSeedance25RequestAspectRatio } from "./BytedanceSeedance25RequestAspectRatio";
import { BytedanceSeedance25RequestResolution } from "./BytedanceSeedance25RequestResolution";
import { ImageReference } from "./ImageReference";
import { VideoReference } from "./VideoReference";
import { WebhookTarget } from "./WebhookTarget";

export const BytedanceSeedance25Request: core.serialization.ObjectSchema<
    serializers.BytedanceSeedance25Request.Raw,
    ElevenLabs.BytedanceSeedance25Request
> = core.serialization.object({
    webhook: WebhookTarget.optional(),
    prompt: core.serialization.string(),
    aspectRatio: core.serialization.property("aspect_ratio", BytedanceSeedance25RequestAspectRatio.optional()),
    resolution: BytedanceSeedance25RequestResolution.optional(),
    durationSecs: core.serialization.property("duration_secs", core.serialization.number().optional()),
    generateAudio: core.serialization.property("generate_audio", core.serialization.boolean().optional()),
    startFrame: core.serialization.property("start_frame", ImageReference.optional()),
    endFrame: core.serialization.property("end_frame", ImageReference.optional()),
    images: core.serialization.list(ImageReference).optional(),
    videos: core.serialization.list(VideoReference).optional(),
    audios: core.serialization.list(AudioReference).optional(),
});

export declare namespace BytedanceSeedance25Request {
    export interface Raw {
        webhook?: WebhookTarget.Raw | null;
        prompt: string;
        aspect_ratio?: BytedanceSeedance25RequestAspectRatio.Raw | null;
        resolution?: BytedanceSeedance25RequestResolution.Raw | null;
        duration_secs?: number | null;
        generate_audio?: boolean | null;
        start_frame?: ImageReference.Raw | null;
        end_frame?: ImageReference.Raw | null;
        images?: ImageReference.Raw[] | null;
        videos?: VideoReference.Raw[] | null;
        audios?: AudioReference.Raw[] | null;
    }
}
