/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import { CaptionStyleSectionAnimationModelEnterType } from "./CaptionStyleSectionAnimationModelEnterType";
import { CaptionStyleSectionAnimationModelExitType } from "./CaptionStyleSectionAnimationModelExitType";

export const CaptionStyleSectionAnimationModel: core.serialization.ObjectSchema<
    serializers.CaptionStyleSectionAnimationModel.Raw,
    ElevenLabs.CaptionStyleSectionAnimationModel
> = core.serialization.object({
    enterType: core.serialization.property("enter_type", CaptionStyleSectionAnimationModelEnterType),
    exitType: core.serialization.property("exit_type", CaptionStyleSectionAnimationModelExitType),
});

export declare namespace CaptionStyleSectionAnimationModel {
    export interface Raw {
        enter_type: CaptionStyleSectionAnimationModelEnterType.Raw;
        exit_type: CaptionStyleSectionAnimationModelExitType.Raw;
    }
}
