// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";

export const ChapterState: core.serialization.Schema<serializers.ChapterState.Raw, ElevenLabs.ChapterState> =
    core.serialization.enum_(["default", "converting"]);

export declare namespace ChapterState {
    export type Raw = "default" | "converting";
}
