// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ChapterContentBlockInputModelSubType } from "./ChapterContentBlockInputModelSubType.js";
import { ChapterContentParagraphTtsNodeInputModel } from "./ChapterContentParagraphTtsNodeInputModel.js";

export const ChapterContentBlockInputModel: core.serialization.ObjectSchema<
    serializers.ChapterContentBlockInputModel.Raw,
    ElevenLabs.ChapterContentBlockInputModel
> = core.serialization.object({
    subType: core.serialization.property("sub_type", ChapterContentBlockInputModelSubType.optional()),
    nodes: core.serialization.list(ChapterContentParagraphTtsNodeInputModel),
    blockId: core.serialization.property("block_id", core.serialization.string().optional()),
});

export declare namespace ChapterContentBlockInputModel {
    export interface Raw {
        sub_type?: ChapterContentBlockInputModelSubType.Raw | null;
        nodes: ChapterContentParagraphTtsNodeInputModel.Raw[];
        block_id?: string | null;
    }
}
