// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ChapterWithContentResponseModelState: core.serialization.Schema<
    serializers.ChapterWithContentResponseModelState.Raw,
    ElevenLabs.ChapterWithContentResponseModelState
> = core.serialization.enum_(["default", "converting"]);

export declare namespace ChapterWithContentResponseModelState {
    export type Raw = "default" | "converting";
}
