// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { ColumnFilterOperation } from "./ColumnFilterOperation";
import { ColumnFilterValuesItem } from "./ColumnFilterValuesItem";

export const ColumnFilter: core.serialization.ObjectSchema<serializers.ColumnFilter.Raw, ElevenLabs.ColumnFilter> =
    core.serialization.object({
        column: core.serialization.string(),
        operation: ColumnFilterOperation,
        values: core.serialization.list(ColumnFilterValuesItem.optional()),
    });

export declare namespace ColumnFilter {
    export interface Raw {
        column: string;
        operation: ColumnFilterOperation.Raw;
        values: (ColumnFilterValuesItem.Raw | null | undefined)[];
    }
}
