// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const ContentThresholdGuardrailThreshold: core.serialization.Schema<
    serializers.ContentThresholdGuardrailThreshold.Raw,
    ElevenLabs.ContentThresholdGuardrailThreshold
> = core.serialization.undiscriminatedUnion([
    core.serialization.number(),
    core.serialization.stringLiteral("low"),
    core.serialization.stringLiteral("medium"),
    core.serialization.stringLiteral("high"),
]);

export declare namespace ContentThresholdGuardrailThreshold {
    export type Raw = number | "low" | "medium" | "high";
}
