// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConversationInitiationSource } from "./ConversationInitiationSource.js";

export const ConversationInitiationSourceInfo: core.serialization.ObjectSchema<
    serializers.ConversationInitiationSourceInfo.Raw,
    ElevenLabs.ConversationInitiationSourceInfo
> = core.serialization.object({
    source: ConversationInitiationSource.optional(),
    version: core.serialization.string().optional(),
});

export declare namespace ConversationInitiationSourceInfo {
    export interface Raw {
        source?: ConversationInitiationSource.Raw | null;
        version?: string | null;
    }
}
