/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import { TtsConversationalConfigOverride } from "./TtsConversationalConfigOverride";
import { ConversationConfigOverride } from "./ConversationConfigOverride";
import { AgentConfigOverride } from "./AgentConfigOverride";

export const ConversationConfigClientOverrideOutput: core.serialization.ObjectSchema<
    serializers.ConversationConfigClientOverrideOutput.Raw,
    ElevenLabs.ConversationConfigClientOverrideOutput
> = core.serialization.object({
    tts: TtsConversationalConfigOverride.optional(),
    conversation: ConversationConfigOverride.optional(),
    agent: AgentConfigOverride.optional(),
});

export declare namespace ConversationConfigClientOverrideOutput {
    export interface Raw {
        tts?: TtsConversationalConfigOverride.Raw | null;
        conversation?: ConversationConfigOverride.Raw | null;
        agent?: AgentConfigOverride.Raw | null;
    }
}
