// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import { ConvAiStoredSecretDependencies } from "./ConvAiStoredSecretDependencies";

export const ConvAiWorkspaceStoredSecretConfig: core.serialization.ObjectSchema<
    serializers.ConvAiWorkspaceStoredSecretConfig.Raw,
    ElevenLabs.ConvAiWorkspaceStoredSecretConfig
> = core.serialization.object({
    type: core.serialization.stringLiteral("stored"),
    secretId: core.serialization.property("secret_id", core.serialization.string()),
    name: core.serialization.string(),
    usedBy: core.serialization.property("used_by", ConvAiStoredSecretDependencies),
});

export declare namespace ConvAiWorkspaceStoredSecretConfig {
    export interface Raw {
        type: "stored";
        secret_id: string;
        name: string;
        used_by: ConvAiStoredSecretDependencies.Raw;
    }
}
