// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AudioReference } from "./AudioReference.js";
import { CreatifyAuroraRequestResolution } from "./CreatifyAuroraRequestResolution.js";
import { ImageReference } from "./ImageReference.js";
import { WebhookTarget } from "./WebhookTarget.js";

export const CreatifyAuroraRequest: core.serialization.ObjectSchema<
    serializers.CreatifyAuroraRequest.Raw,
    ElevenLabs.CreatifyAuroraRequest
> = core.serialization.object({
    webhook: WebhookTarget.optional(),
    image: ImageReference,
    audio: AudioReference,
    resolution: CreatifyAuroraRequestResolution.optional(),
    guidanceScale: core.serialization.property("guidance_scale", core.serialization.number().optional()),
    audioGuidanceScale: core.serialization.property("audio_guidance_scale", core.serialization.number().optional()),
});

export declare namespace CreatifyAuroraRequest {
    export interface Raw {
        webhook?: WebhookTarget.Raw | null;
        image: ImageReference.Raw;
        audio: AudioReference.Raw;
        resolution?: CreatifyAuroraRequestResolution.Raw | null;
        guidance_scale?: number | null;
        audio_guidance_scale?: number | null;
    }
}
