// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import * as serializers from "../index";

export const CustomToolApiSchemaConfig: core.serialization.ObjectSchema<
    serializers.CustomToolApiSchemaConfig.Raw,
    ElevenLabs.CustomToolApiSchemaConfig
> = core.serialization.object({
    requestBodySchema: core.serialization.property(
        "request_body_schema",
        core.serialization.lazyObject(() => serializers.ObjectJsonSchemaPropertyOutput),
    ),
});

export declare namespace CustomToolApiSchemaConfig {
    export interface Raw {
        request_body_schema: serializers.ObjectJsonSchemaPropertyOutput.Raw;
    }
}
