// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConvAiEnvVarLocator } from "./ConvAiEnvVarLocator.js";
import { ConvAiSecretLocator } from "./ConvAiSecretLocator.js";

export const CustomLlmApiKey: core.serialization.Schema<serializers.CustomLlmApiKey.Raw, ElevenLabs.CustomLlmApiKey> =
    core.serialization.undiscriminatedUnion([ConvAiSecretLocator, ConvAiEnvVarLocator]);

export declare namespace CustomLlmApiKey {
    export type Raw = ConvAiSecretLocator.Raw | ConvAiEnvVarLocator.Raw;
}
