// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";

export const DeleteChapterResponseModel: core.serialization.ObjectSchema<
    serializers.DeleteChapterResponseModel.Raw,
    ElevenLabs.DeleteChapterResponseModel
> = core.serialization.object({
    status: core.serialization.string(),
});

export declare namespace DeleteChapterResponseModel {
    export interface Raw {
        status: string;
    }
}
