// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const DtmfInputConfig: core.serialization.ObjectSchema<
    serializers.DtmfInputConfig.Raw,
    ElevenLabs.DtmfInputConfig
> = core.serialization.object({
    dtmfInputTimeout: core.serialization.property("dtmf_input_timeout", core.serialization.number().optional()),
    hashTerminator: core.serialization.property("hash_terminator", core.serialization.boolean().optional()),
});

export declare namespace DtmfInputConfig {
    export interface Raw {
        dtmf_input_timeout?: number | null;
        hash_terminator?: boolean | null;
    }
}
