// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const DubbingTranscriptSegment: core.serialization.ObjectSchema<
    serializers.DubbingTranscriptSegment.Raw,
    ElevenLabs.DubbingTranscriptSegment
> = core.serialization.object({
    id: core.serialization.string(),
    text: core.serialization.string(),
    speakerId: core.serialization.property("speaker_id", core.serialization.string()),
    startS: core.serialization.property("start_s", core.serialization.number()),
    endS: core.serialization.property("end_s", core.serialization.number()),
    externalId: core.serialization.property("external_id", core.serialization.string().optional()),
});

export declare namespace DubbingTranscriptSegment {
    export interface Raw {
        id: string;
        text: string;
        speaker_id: string;
        start_s: number;
        end_s: number;
        external_id?: string | null;
    }
}
