// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const DubbingStatusStatus: core.serialization.Schema<
    serializers.DubbingStatusStatus.Raw,
    ElevenLabs.DubbingStatusStatus
> = core.serialization.enum_(["started", "stopped"]);

export declare namespace DubbingStatusStatus {
    export type Raw = "started" | "stopped";
}
