// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { DubbingTranscriptWord } from "./DubbingTranscriptWord";

export const DubbingTranscriptUtterance: core.serialization.ObjectSchema<
    serializers.DubbingTranscriptUtterance.Raw,
    ElevenLabs.DubbingTranscriptUtterance
> = core.serialization.object({
    text: core.serialization.string().optional(),
    speakerId: core.serialization.property("speaker_id", core.serialization.string().optional()),
    startS: core.serialization.property("start_s", core.serialization.number().optional()),
    endS: core.serialization.property("end_s", core.serialization.number().optional()),
    words: core.serialization.list(DubbingTranscriptWord).optional(),
});

export declare namespace DubbingTranscriptUtterance {
    export interface Raw {
        text?: string | null;
        speaker_id?: string | null;
        start_s?: number | null;
        end_s?: number | null;
        words?: DubbingTranscriptWord.Raw[] | null;
    }
}
