// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const DubbingRenderResponseModel: core.serialization.ObjectSchema<
    serializers.DubbingRenderResponseModel.Raw,
    ElevenLabs.DubbingRenderResponseModel
> = core.serialization.object({
    version: core.serialization.number(),
    renderId: core.serialization.property("render_id", core.serialization.string()),
});

export declare namespace DubbingRenderResponseModel {
    export interface Raw {
        version: number;
        render_id: string;
    }
}
