// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const EditVoiceSettingsRequest: core.serialization.Schema<
    serializers.EditVoiceSettingsRequest.Raw,
    ElevenLabs.EditVoiceSettingsRequest
> = core.serialization.unknown();

export declare namespace EditVoiceSettingsRequest {
    export type Raw = unknown;
}
