/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";

export const EmbeddingModelEnum: core.serialization.Schema<
    serializers.EmbeddingModelEnum.Raw,
    ElevenLabs.EmbeddingModelEnum
> = core.serialization.enum_(["e5_mistral_7b_instruct", "multilingual_e5_large_instruct"]);

export declare namespace EmbeddingModelEnum {
    export type Raw = "e5_mistral_7b_instruct" | "multilingual_e5_large_instruct";
}
