// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";

export const EndCallToolConfig: core.serialization.ObjectSchema<
    serializers.EndCallToolConfig.Raw,
    ElevenLabs.EndCallToolConfig
> = core.serialization.object({});

export declare namespace EndCallToolConfig {
    export interface Raw {}
}
