// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { PromptEvaluationCriteria } from "./PromptEvaluationCriteria";

export const EvaluationSettingsOutput: core.serialization.ObjectSchema<
    serializers.EvaluationSettingsOutput.Raw,
    ElevenLabs.EvaluationSettingsOutput
> = core.serialization.object({
    criteria: core.serialization.list(PromptEvaluationCriteria).optional(),
});

export declare namespace EvaluationSettingsOutput {
    export interface Raw {
        criteria?: PromptEvaluationCriteria.Raw[] | null;
    }
}
