// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const ExperimentAssignmentSource: core.serialization.Schema<
    serializers.ExperimentAssignmentSource.Raw,
    ElevenLabs.ExperimentAssignmentSource
> = core.serialization.enum_(["server_branch", "client_declared"]);

export declare namespace ExperimentAssignmentSource {
    export type Raw = "server_branch" | "client_declared";
}
