// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const ExternalSyncType: core.serialization.Schema<
    serializers.ExternalSyncType.Raw,
    ElevenLabs.ExternalSyncType
> = core.serialization.stringLiteral("google_drive");

export declare namespace ExternalSyncType {
    export type Raw = "google_drive";
}
