// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CrawlStatus } from "./CrawlStatus.js";

export const FileRefreshStatus: core.serialization.ObjectSchema<
    serializers.FileRefreshStatus.Raw,
    ElevenLabs.FileRefreshStatus
> = core.serialization.object({
    status: CrawlStatus.optional(),
    enqueuedAt: core.serialization.property("enqueued_at", core.serialization.number().optional()),
    startedAt: core.serialization.property("started_at", core.serialization.number().optional()),
    completedAt: core.serialization.property("completed_at", core.serialization.number().optional()),
    lastSyncedAt: core.serialization.property("last_synced_at", core.serialization.number().optional()),
    errorMessage: core.serialization.property("error_message", core.serialization.string().optional()),
});

export declare namespace FileRefreshStatus {
    export interface Raw {
        status?: CrawlStatus.Raw | null;
        enqueued_at?: number | null;
        started_at?: number | null;
        completed_at?: number | null;
        last_synced_at?: number | null;
        error_message?: string | null;
    }
}
