// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const FinetuneVisibility: core.serialization.Schema<
    serializers.FinetuneVisibility.Raw,
    ElevenLabs.FinetuneVisibility
> = core.serialization.enum_(["private", "workspace", "public"]);

export declare namespace FinetuneVisibility {
    export type Raw = "private" | "workspace" | "public";
}
