/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";

export const ForcedAlignmentWordResponseModel: core.serialization.ObjectSchema<
    serializers.ForcedAlignmentWordResponseModel.Raw,
    ElevenLabs.ForcedAlignmentWordResponseModel
> = core.serialization.object({
    text: core.serialization.string(),
    start: core.serialization.number(),
    end: core.serialization.number(),
    loss: core.serialization.number(),
});

export declare namespace ForcedAlignmentWordResponseModel {
    export interface Raw {
        text: string;
        start: number;
        end: number;
        loss: number;
    }
}
