// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ForcedAlignmentCharacterResponseModel } from "./ForcedAlignmentCharacterResponseModel.js";
import { ForcedAlignmentWordResponseModel } from "./ForcedAlignmentWordResponseModel.js";

export const ForcedAlignmentResponseModel: core.serialization.ObjectSchema<
    serializers.ForcedAlignmentResponseModel.Raw,
    ElevenLabs.ForcedAlignmentResponseModel
> = core.serialization.object({
    characters: core.serialization.list(ForcedAlignmentCharacterResponseModel),
    words: core.serialization.list(ForcedAlignmentWordResponseModel),
    loss: core.serialization.number(),
});

export declare namespace ForcedAlignmentResponseModel {
    export interface Raw {
        characters: ForcedAlignmentCharacterResponseModel.Raw[];
        words: ForcedAlignmentWordResponseModel.Raw[];
        loss: number;
    }
}
