// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const GetAnalyticsSummaryParams: core.serialization.ObjectSchema<
    serializers.GetAnalyticsSummaryParams.Raw,
    ElevenLabs.GetAnalyticsSummaryParams
> = core.serialization.object({
    smbToolType: core.serialization.property(
        "smb_tool_type",
        core.serialization.stringLiteral("get_analytics_summary").optional(),
    ),
});

export declare namespace GetAnalyticsSummaryParams {
    export interface Raw {
        smb_tool_type?: "get_analytics_summary" | null;
    }
}
