// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { GetPhoneNumberSipTrunkResponseModel } from "./GetPhoneNumberSipTrunkResponseModel";
import { GetPhoneNumberTwilioResponseModel } from "./GetPhoneNumberTwilioResponseModel";

export const GetAgentResponseModelPhoneNumbersItem: core.serialization.Schema<
    serializers.GetAgentResponseModelPhoneNumbersItem.Raw,
    ElevenLabs.GetAgentResponseModelPhoneNumbersItem
> = core.serialization
    .union("provider", {
        sip_trunk: GetPhoneNumberSipTrunkResponseModel,
        twilio: GetPhoneNumberTwilioResponseModel,
    })
    .transform<ElevenLabs.GetAgentResponseModelPhoneNumbersItem>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace GetAgentResponseModelPhoneNumbersItem {
    export type Raw = GetAgentResponseModelPhoneNumbersItem.SipTrunk | GetAgentResponseModelPhoneNumbersItem.Twilio;

    export interface SipTrunk extends GetPhoneNumberSipTrunkResponseModel.Raw {
        provider: "sip_trunk";
    }

    export interface Twilio extends GetPhoneNumberTwilioResponseModel.Raw {
        provider: "twilio";
    }
}
