// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const GetChaptersRequest: core.serialization.Schema<
    serializers.GetChaptersRequest.Raw,
    ElevenLabs.GetChaptersRequest
> = core.serialization.unknown();

export declare namespace GetChaptersRequest {
    export type Raw = unknown;
}
