// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const GetPronunciationDictionaryMetadataResponsePermissionOnResource: core.serialization.Schema<
    serializers.GetPronunciationDictionaryMetadataResponsePermissionOnResource.Raw,
    ElevenLabs.GetPronunciationDictionaryMetadataResponsePermissionOnResource
> = core.serialization.enum_(["admin", "editor", "commenter", "viewer"]);

export declare namespace GetPronunciationDictionaryMetadataResponsePermissionOnResource {
    export type Raw = "admin" | "editor" | "commenter" | "viewer";
}
