// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const GetPronunciationDictionaryResponse: core.serialization.Schema<
    serializers.GetPronunciationDictionaryResponse.Raw,
    ElevenLabs.GetPronunciationDictionaryResponse
> = core.serialization.unknown();

export declare namespace GetPronunciationDictionaryResponse {
    export type Raw = unknown;
}
