/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import { PhoneNumberAgentInfo } from "./PhoneNumberAgentInfo";
import { GetPhoneNumberOutboundSipTrunkConfigResponseModel } from "./GetPhoneNumberOutboundSipTrunkConfigResponseModel";
import { GetPhoneNumberInboundSipTrunkConfigResponseModel } from "./GetPhoneNumberInboundSipTrunkConfigResponseModel";
import { LivekitStackType } from "./LivekitStackType";

export const GetPhoneNumberSipTrunkResponseModel: core.serialization.ObjectSchema<
    serializers.GetPhoneNumberSipTrunkResponseModel.Raw,
    ElevenLabs.GetPhoneNumberSipTrunkResponseModel
> = core.serialization.object({
    phoneNumber: core.serialization.property("phone_number", core.serialization.string()),
    label: core.serialization.string(),
    supportsInbound: core.serialization.property("supports_inbound", core.serialization.boolean().optional()),
    supportsOutbound: core.serialization.property("supports_outbound", core.serialization.boolean().optional()),
    phoneNumberId: core.serialization.property("phone_number_id", core.serialization.string()),
    assignedAgent: core.serialization.property("assigned_agent", PhoneNumberAgentInfo.optional()),
    providerConfig: core.serialization.property(
        "provider_config",
        GetPhoneNumberOutboundSipTrunkConfigResponseModel.optional(),
    ),
    outboundTrunk: core.serialization.property(
        "outbound_trunk",
        GetPhoneNumberOutboundSipTrunkConfigResponseModel.optional(),
    ),
    inboundTrunk: core.serialization.property(
        "inbound_trunk",
        GetPhoneNumberInboundSipTrunkConfigResponseModel.optional(),
    ),
    livekitStack: core.serialization.property("livekit_stack", LivekitStackType),
});

export declare namespace GetPhoneNumberSipTrunkResponseModel {
    export interface Raw {
        phone_number: string;
        label: string;
        supports_inbound?: boolean | null;
        supports_outbound?: boolean | null;
        phone_number_id: string;
        assigned_agent?: PhoneNumberAgentInfo.Raw | null;
        provider_config?: GetPhoneNumberOutboundSipTrunkConfigResponseModel.Raw | null;
        outbound_trunk?: GetPhoneNumberOutboundSipTrunkConfigResponseModel.Raw | null;
        inbound_trunk?: GetPhoneNumberInboundSipTrunkConfigResponseModel.Raw | null;
        livekit_stack: LivekitStackType.Raw;
    }
}
