// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { AgentFailureResponseExample } from "./AgentFailureResponseExample";
import { AgentSuccessfulResponseExample } from "./AgentSuccessfulResponseExample";
import { ConversationHistoryTranscriptCommonModelOutput } from "./ConversationHistoryTranscriptCommonModelOutput";
import { GetResponseUnitTestResponseModelDynamicVariablesValue } from "./GetResponseUnitTestResponseModelDynamicVariablesValue";
import { TestFromConversationMetadataOutput } from "./TestFromConversationMetadataOutput";

export const GetResponseUnitTestResponseModel: core.serialization.ObjectSchema<
    serializers.GetResponseUnitTestResponseModel.Raw,
    ElevenLabs.GetResponseUnitTestResponseModel
> = core.serialization.object({
    fromConversationMetadata: core.serialization.property(
        "from_conversation_metadata",
        TestFromConversationMetadataOutput.optional(),
    ),
    dynamicVariables: core.serialization.property(
        "dynamic_variables",
        core.serialization
            .record(core.serialization.string(), GetResponseUnitTestResponseModelDynamicVariablesValue.optional())
            .optional(),
    ),
    chatHistory: core.serialization.property(
        "chat_history",
        core.serialization.list(ConversationHistoryTranscriptCommonModelOutput).optional(),
    ),
    successCondition: core.serialization.property("success_condition", core.serialization.string().optional()),
    successExamples: core.serialization.property(
        "success_examples",
        core.serialization.list(AgentSuccessfulResponseExample).optional(),
    ),
    failureExamples: core.serialization.property(
        "failure_examples",
        core.serialization.list(AgentFailureResponseExample).optional(),
    ),
    id: core.serialization.string(),
    name: core.serialization.string(),
});

export declare namespace GetResponseUnitTestResponseModel {
    export interface Raw {
        from_conversation_metadata?: TestFromConversationMetadataOutput.Raw | null;
        dynamic_variables?: Record<
            string,
            GetResponseUnitTestResponseModelDynamicVariablesValue.Raw | null | undefined
        > | null;
        chat_history?: ConversationHistoryTranscriptCommonModelOutput.Raw[] | null;
        success_condition?: string | null;
        success_examples?: AgentSuccessfulResponseExample.Raw[] | null;
        failure_examples?: AgentFailureResponseExample.Raw[] | null;
        id: string;
        name: string;
    }
}
