// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { DependentAvailableToolIdentifier } from "./DependentAvailableToolIdentifier";
import { DependentUnknownToolIdentifier } from "./DependentUnknownToolIdentifier";

export const GetSecretDependenciesResponseModelDependenciesZeroItem: core.serialization.Schema<
    serializers.GetSecretDependenciesResponseModelDependenciesZeroItem.Raw,
    ElevenLabs.GetSecretDependenciesResponseModelDependenciesZeroItem
> = core.serialization
    .union("type", {
        available: DependentAvailableToolIdentifier,
        unknown: DependentUnknownToolIdentifier,
    })
    .transform<ElevenLabs.GetSecretDependenciesResponseModelDependenciesZeroItem>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace GetSecretDependenciesResponseModelDependenciesZeroItem {
    export type Raw =
        | GetSecretDependenciesResponseModelDependenciesZeroItem.Available
        | GetSecretDependenciesResponseModelDependenciesZeroItem.Unknown;

    export interface Available extends DependentAvailableToolIdentifier.Raw {
        type: "available";
    }

    export interface Unknown extends DependentUnknownToolIdentifier.Raw {
        type: "unknown";
    }
}
