// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { UnitTestSummaryResponseModel } from "./UnitTestSummaryResponseModel.js";

export const GetTestsSummariesByIdsResponseModel: core.serialization.ObjectSchema<
    serializers.GetTestsSummariesByIdsResponseModel.Raw,
    ElevenLabs.GetTestsSummariesByIdsResponseModel
> = core.serialization.object({
    tests: core.serialization.record(core.serialization.string(), UnitTestSummaryResponseModel),
});

export declare namespace GetTestsSummariesByIdsResponseModel {
    export interface Raw {
        tests: Record<string, UnitTestSummaryResponseModel.Raw>;
    }
}
