// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import { UnitTestSummaryResponseModel } from "./UnitTestSummaryResponseModel";

export const GetTestsSummariesByIdsResponseModel: core.serialization.ObjectSchema<
    serializers.GetTestsSummariesByIdsResponseModel.Raw,
    ElevenLabs.GetTestsSummariesByIdsResponseModel
> = core.serialization.object({
    tests: core.serialization.record(core.serialization.string(), UnitTestSummaryResponseModel),
});

export declare namespace GetTestsSummariesByIdsResponseModel {
    export interface Raw {
        tests: Record<string, UnitTestSummaryResponseModel.Raw>;
    }
}
