// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const GptImage1RequestQuality: core.serialization.Schema<
    serializers.GptImage1RequestQuality.Raw,
    ElevenLabs.GptImage1RequestQuality
> = core.serialization.enum_(["low", "medium", "high"]);

export declare namespace GptImage1RequestQuality {
    export type Raw = "low" | "medium" | "high";
}
