// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const GptImage15RequestBackground: core.serialization.Schema<
    serializers.GptImage15RequestBackground.Raw,
    ElevenLabs.GptImage15RequestBackground
> = core.serialization.enum_(["transparent", "opaque", "auto"]);

export declare namespace GptImage15RequestBackground {
    export type Raw = "transparent" | "opaque" | "auto";
}
