// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import { ModerationGuardrailInput } from "./ModerationGuardrailInput";

export const GuardrailsV1Input: core.serialization.ObjectSchema<
    serializers.GuardrailsV1Input.Raw,
    ElevenLabs.GuardrailsV1Input
> = core.serialization.object({
    version: core.serialization.stringLiteral("1").optional(),
    moderation: ModerationGuardrailInput.optional(),
});

export declare namespace GuardrailsV1Input {
    export interface Raw {
        version?: "1" | null;
        moderation?: ModerationGuardrailInput.Raw | null;
    }
}
