// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const Init: core.serialization.ObjectSchema<serializers.Init.Raw, ElevenLabs.Init> = core.serialization.object({
    type: core.serialization.stringLiteral("init"),
    conversationId: core.serialization.property("conversation_id", core.serialization.string()),
});

export declare namespace Init {
    export interface Raw {
        type: "init";
        conversation_id: string;
    }
}
