// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import { RealtimeVoiceSettings } from "./RealtimeVoiceSettings";
import { GenerationConfig } from "./GenerationConfig";
import { PronunciationDictionaryLocator } from "./PronunciationDictionaryLocator";

export const InitializeConnectionMulti: core.serialization.ObjectSchema<
    serializers.InitializeConnectionMulti.Raw,
    ElevenLabs.InitializeConnectionMulti
> = core.serialization.object({
    text: core.serialization.stringLiteral(" "),
    voiceSettings: core.serialization.property("voice_settings", RealtimeVoiceSettings.optional()),
    generationConfig: core.serialization.property("generation_config", GenerationConfig.optional()),
    pronunciationDictionaryLocators: core.serialization.property(
        "pronunciation_dictionary_locators",
        core.serialization.list(PronunciationDictionaryLocator).optional(),
    ),
    xiApiKey: core.serialization.property("xi_api_key", core.serialization.string().optional()),
    authorization: core.serialization.string().optional(),
    contextId: core.serialization.property("context_id", core.serialization.string().optional()),
});

export declare namespace InitializeConnectionMulti {
    export interface Raw {
        text: " ";
        voice_settings?: RealtimeVoiceSettings.Raw | null;
        generation_config?: GenerationConfig.Raw | null;
        pronunciation_dictionary_locators?: PronunciationDictionaryLocator.Raw[] | null;
        xi_api_key?: string | null;
        authorization?: string | null;
        context_id?: string | null;
    }
}
