// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { InitializeConnectionMultiGenerationConfig } from "./InitializeConnectionMultiGenerationConfig.js";
import { InitializeConnectionMultiPronunciationDictionaryLocatorsItem } from "./InitializeConnectionMultiPronunciationDictionaryLocatorsItem.js";
import { InitializeConnectionMultiVoiceSettings } from "./InitializeConnectionMultiVoiceSettings.js";

export const InitializeConnectionMulti: core.serialization.ObjectSchema<
    serializers.InitializeConnectionMulti.Raw,
    ElevenLabs.InitializeConnectionMulti
> = core.serialization.object({
    text: core.serialization.stringLiteral(" "),
    voiceSettings: core.serialization.property("voice_settings", InitializeConnectionMultiVoiceSettings.optional()),
    generationConfig: core.serialization.property(
        "generation_config",
        InitializeConnectionMultiGenerationConfig.optional(),
    ),
    pronunciationDictionaryLocators: core.serialization.property(
        "pronunciation_dictionary_locators",
        core.serialization.list(InitializeConnectionMultiPronunciationDictionaryLocatorsItem).optional(),
    ),
    xiApiKey: core.serialization.property("xi_api_key", core.serialization.string().optional()),
    authorization: core.serialization.string().optional(),
    contextId: core.serialization.property("context_id", core.serialization.string().optional()),
});

export declare namespace InitializeConnectionMulti {
    export interface Raw {
        text: " ";
        voice_settings?: InitializeConnectionMultiVoiceSettings.Raw | null;
        generation_config?: InitializeConnectionMultiGenerationConfig.Raw | null;
        pronunciation_dictionary_locators?: InitializeConnectionMultiPronunciationDictionaryLocatorsItem.Raw[] | null;
        xi_api_key?: string | null;
        authorization?: string | null;
        context_id?: string | null;
    }
}
