// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const KnowledgeBaseDependentType: core.serialization.Schema<
    serializers.KnowledgeBaseDependentType.Raw,
    ElevenLabs.KnowledgeBaseDependentType
> = core.serialization.enum_(["direct", "transitive", "all"]);

export declare namespace KnowledgeBaseDependentType {
    export type Raw = "direct" | "transitive" | "all";
}
