// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { KnowledgeBaseDeletedResponseModel } from "./KnowledgeBaseDeletedResponseModel.js";

export const KnowledgeBaseBulkDeleteSuccessfulResponseModel: core.serialization.ObjectSchema<
    serializers.KnowledgeBaseBulkDeleteSuccessfulResponseModel.Raw,
    ElevenLabs.KnowledgeBaseBulkDeleteSuccessfulResponseModel
> = core.serialization.object({
    data: KnowledgeBaseDeletedResponseModel,
});

export declare namespace KnowledgeBaseBulkDeleteSuccessfulResponseModel {
    export interface Raw {
        data: KnowledgeBaseDeletedResponseModel.Raw;
    }
}
