// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const KnowledgeBaseRagToolStatus: core.serialization.Schema<
    serializers.KnowledgeBaseRagToolStatus.Raw,
    ElevenLabs.KnowledgeBaseRagToolStatus
> = core.serialization.enum_(["success", "no_documents", "no_results"]);

export declare namespace KnowledgeBaseRagToolStatus {
    export type Raw = "success" | "no_documents" | "no_results";
}
