// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const LanguageInfo: core.serialization.ObjectSchema<serializers.LanguageInfo.Raw, ElevenLabs.LanguageInfo> =
    core.serialization.object({
        code: core.serialization.string(),
        label: core.serialization.string(),
    });

export declare namespace LanguageInfo {
    export interface Raw {
        code: string;
        label: string;
    }
}
