// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConversationConfigClientOverrideInput } from "./ConversationConfigClientOverrideInput.js";
import { LanguagePresetTranslation } from "./LanguagePresetTranslation.js";

export const LanguagePresetInput: core.serialization.ObjectSchema<
    serializers.LanguagePresetInput.Raw,
    ElevenLabs.LanguagePresetInput
> = core.serialization.object({
    overrides: ConversationConfigClientOverrideInput,
    firstMessageTranslation: core.serialization.property(
        "first_message_translation",
        LanguagePresetTranslation.optional(),
    ),
    softTimeoutTranslation: core.serialization.property(
        "soft_timeout_translation",
        LanguagePresetTranslation.optional(),
    ),
});

export declare namespace LanguagePresetInput {
    export interface Raw {
        overrides: ConversationConfigClientOverrideInput.Raw;
        first_message_translation?: LanguagePresetTranslation.Raw | null;
        soft_timeout_translation?: LanguagePresetTranslation.Raw | null;
    }
}
