// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentBranchSummary } from "./AgentBranchSummary.js";
import { ListResponseMeta } from "./ListResponseMeta.js";

export const ListResponseAgentBranchSummary: core.serialization.ObjectSchema<
    serializers.ListResponseAgentBranchSummary.Raw,
    ElevenLabs.ListResponseAgentBranchSummary
> = core.serialization.object({
    meta: ListResponseMeta.optional(),
    results: core.serialization.list(AgentBranchSummary),
});

export declare namespace ListResponseAgentBranchSummary {
    export interface Raw {
        meta?: ListResponseMeta.Raw | null;
        results: AgentBranchSummary.Raw[];
    }
}
