/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import { LiteralJsonSchemaPropertyType } from "./LiteralJsonSchemaPropertyType";
import { LiteralJsonSchemaPropertyConstantValue } from "./LiteralJsonSchemaPropertyConstantValue";

export const LiteralJsonSchemaProperty: core.serialization.ObjectSchema<
    serializers.LiteralJsonSchemaProperty.Raw,
    ElevenLabs.LiteralJsonSchemaProperty
> = core.serialization.object({
    type: LiteralJsonSchemaPropertyType,
    description: core.serialization.string().optional(),
    enum: core.serialization.list(core.serialization.string()).optional(),
    dynamicVariable: core.serialization.property("dynamic_variable", core.serialization.string().optional()),
    constantValue: core.serialization.property("constant_value", LiteralJsonSchemaPropertyConstantValue.optional()),
});

export declare namespace LiteralJsonSchemaProperty {
    export interface Raw {
        type: LiteralJsonSchemaPropertyType.Raw;
        description?: string | null;
        enum?: string[] | null;
        dynamic_variable?: string | null;
        constant_value?: LiteralJsonSchemaPropertyConstantValue.Raw | null;
    }
}
