// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const MergeProposalCloseReason: core.serialization.Schema<
    serializers.MergeProposalCloseReason.Raw,
    ElevenLabs.MergeProposalCloseReason
> = core.serialization.enum_(["withdrawn", "rejected", "branch_archived"]);

export declare namespace MergeProposalCloseReason {
    export type Raw = "withdrawn" | "rejected" | "branch_archived";
}
