// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { DetailedMusicResponse } from "./DetailedMusicResponse";

export const MultipartMusicResponse: core.serialization.ObjectSchema<
    serializers.MultipartMusicResponse.Raw,
    ElevenLabs.MultipartMusicResponse
> = core.serialization.object({
    metadata: DetailedMusicResponse,
    audio: core.serialization.string(),
});

export declare namespace MultipartMusicResponse {
    export interface Raw {
        metadata: DetailedMusicResponse.Raw;
        audio: string;
    }
}
