// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { OpenAiAudioOutputFormat } from "./OpenAiAudioOutputFormat";

export const OpenAiAudioOutputConfig: core.serialization.ObjectSchema<
    serializers.OpenAiAudioOutputConfig.Raw,
    ElevenLabs.OpenAiAudioOutputConfig
> = core.serialization.object({
    format: OpenAiAudioOutputFormat.optional(),
    voice: core.serialization.string().optional(),
});

export declare namespace OpenAiAudioOutputConfig {
    export interface Raw {
        format?: OpenAiAudioOutputFormat.Raw | null;
        voice?: string | null;
    }
}
