// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { MockingStrategy } from "./MockingStrategy";
import { MockNoMatchBehavior } from "./MockNoMatchBehavior";

export const OrchestratorToolMockBehaviorConfig: core.serialization.ObjectSchema<
    serializers.OrchestratorToolMockBehaviorConfig.Raw,
    ElevenLabs.OrchestratorToolMockBehaviorConfig
> = core.serialization.object({
    mockingStrategy: core.serialization.property("mocking_strategy", MockingStrategy.optional()),
    fallbackStrategy: core.serialization.property("fallback_strategy", MockNoMatchBehavior.optional()),
    mockedToolNames: core.serialization.property(
        "mocked_tool_names",
        core.serialization.list(core.serialization.string()).optional(),
    ),
});

export declare namespace OrchestratorToolMockBehaviorConfig {
    export interface Raw {
        mocking_strategy?: MockingStrategy.Raw | null;
        fallback_strategy?: MockNoMatchBehavior.Raw | null;
        mocked_tool_names?: string[] | null;
    }
}
