// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const PendingClipTaskType: core.serialization.Schema<
    serializers.PendingClipTaskType.Raw,
    ElevenLabs.PendingClipTaskType
> = core.serialization.enum_(["preprocessing", "speech_import", "dubbing"]);

export declare namespace PendingClipTaskType {
    export type Raw = "preprocessing" | "speech_import" | "dubbing";
}
