// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import { PendingSubscriptionSwitchResponseModelNextTier } from "./PendingSubscriptionSwitchResponseModelNextTier";

export const PendingSubscriptionSwitchResponseModel: core.serialization.ObjectSchema<
    serializers.PendingSubscriptionSwitchResponseModel.Raw,
    ElevenLabs.PendingSubscriptionSwitchResponseModel
> = core.serialization.object({
    kind: core.serialization.stringLiteral("change").optional(),
    nextTier: core.serialization.property("next_tier", PendingSubscriptionSwitchResponseModelNextTier),
    timestampSeconds: core.serialization.property("timestamp_seconds", core.serialization.number()),
});

export declare namespace PendingSubscriptionSwitchResponseModel {
    export interface Raw {
        kind?: "change" | null;
        next_tier: PendingSubscriptionSwitchResponseModelNextTier.Raw;
        timestamp_seconds: number;
    }
}
