// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { PostDialDigitsDynamicVariable } from "./PostDialDigitsDynamicVariable";
import { PostDialDigitsStatic } from "./PostDialDigitsStatic";

export const PhoneNumberTransferPostDialDigits: core.serialization.Schema<
    serializers.PhoneNumberTransferPostDialDigits.Raw,
    ElevenLabs.PhoneNumberTransferPostDialDigits
> = core.serialization
    .union("type", {
        dynamic: PostDialDigitsDynamicVariable,
        static: PostDialDigitsStatic,
    })
    .transform<ElevenLabs.PhoneNumberTransferPostDialDigits>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace PhoneNumberTransferPostDialDigits {
    export type Raw = PhoneNumberTransferPostDialDigits.Dynamic | PhoneNumberTransferPostDialDigits.Static;

    export interface Dynamic extends PostDialDigitsDynamicVariable.Raw {
        type: "dynamic";
    }

    export interface Static extends PostDialDigitsStatic.Raw {
        type: "static";
    }
}
