// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const PhoneNumberDynamicVariableTransferDestination: core.serialization.ObjectSchema<
    serializers.PhoneNumberDynamicVariableTransferDestination.Raw,
    ElevenLabs.PhoneNumberDynamicVariableTransferDestination
> = core.serialization.object({
    phoneNumber: core.serialization.property("phone_number", core.serialization.string()),
});

export declare namespace PhoneNumberDynamicVariableTransferDestination {
    export interface Raw {
        phone_number: string;
    }
}
