// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { CustomSipHeader } from "./CustomSipHeader";
import { CustomSipHeaderWithDynamicVariable } from "./CustomSipHeaderWithDynamicVariable";

export const PhoneNumberTransferCustomSipHeadersItem: core.serialization.Schema<
    serializers.PhoneNumberTransferCustomSipHeadersItem.Raw,
    ElevenLabs.PhoneNumberTransferCustomSipHeadersItem
> = core.serialization
    .union("type", {
        dynamic: CustomSipHeaderWithDynamicVariable,
        static: CustomSipHeader,
    })
    .transform<ElevenLabs.PhoneNumberTransferCustomSipHeadersItem>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace PhoneNumberTransferCustomSipHeadersItem {
    export type Raw = PhoneNumberTransferCustomSipHeadersItem.Dynamic | PhoneNumberTransferCustomSipHeadersItem.Static;

    export interface Dynamic extends CustomSipHeaderWithDynamicVariable.Raw {
        type: "dynamic";
    }

    export interface Static extends CustomSipHeader.Raw {
        type: "static";
    }
}
