// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";

export const PhoneNumberDynamicVariableTransferDestination: core.serialization.ObjectSchema<
    serializers.PhoneNumberDynamicVariableTransferDestination.Raw,
    ElevenLabs.PhoneNumberDynamicVariableTransferDestination
> = core.serialization.object({
    phoneNumber: core.serialization.property("phone_number", core.serialization.string()),
});

export declare namespace PhoneNumberDynamicVariableTransferDestination {
    export interface Raw {
        phone_number: string;
    }
}
