// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";

export const PostWorkspaceSecretResponseModel: core.serialization.ObjectSchema<
    serializers.PostWorkspaceSecretResponseModel.Raw,
    ElevenLabs.PostWorkspaceSecretResponseModel
> = core.serialization.object({
    type: core.serialization.stringLiteral("stored"),
    secretId: core.serialization.property("secret_id", core.serialization.string()),
    name: core.serialization.string(),
});

export declare namespace PostWorkspaceSecretResponseModel {
    export interface Raw {
        type: "stored";
        secret_id: string;
        name: string;
    }
}
