// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ProjectResponseTargetAudience: core.serialization.Schema<
    serializers.ProjectResponseTargetAudience.Raw,
    ElevenLabs.ProjectResponseTargetAudience
> = core.serialization.enum_(["children", "young adult", "adult", "all ages"]);

export declare namespace ProjectResponseTargetAudience {
    export type Raw = "children" | "young adult" | "adult" | "all ages";
}
