// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import { PronunciationDictionaryVersionResponseModelPermissionOnResource } from "./PronunciationDictionaryVersionResponseModelPermissionOnResource";

export const PronunciationDictionaryVersionResponseModel: core.serialization.ObjectSchema<
    serializers.PronunciationDictionaryVersionResponseModel.Raw,
    ElevenLabs.PronunciationDictionaryVersionResponseModel
> = core.serialization.object({
    versionId: core.serialization.property("version_id", core.serialization.string()),
    versionRulesNum: core.serialization.property("version_rules_num", core.serialization.number()),
    pronunciationDictionaryId: core.serialization.property("pronunciation_dictionary_id", core.serialization.string()),
    dictionaryName: core.serialization.property("dictionary_name", core.serialization.string()),
    versionName: core.serialization.property("version_name", core.serialization.string()),
    permissionOnResource: core.serialization.property(
        "permission_on_resource",
        PronunciationDictionaryVersionResponseModelPermissionOnResource.optional(),
    ),
    createdBy: core.serialization.property("created_by", core.serialization.string()),
    creationTimeUnix: core.serialization.property("creation_time_unix", core.serialization.number()),
    archivedTimeUnix: core.serialization.property("archived_time_unix", core.serialization.number().optional()),
});

export declare namespace PronunciationDictionaryVersionResponseModel {
    export interface Raw {
        version_id: string;
        version_rules_num: number;
        pronunciation_dictionary_id: string;
        dictionary_name: string;
        version_name: string;
        permission_on_resource?: PronunciationDictionaryVersionResponseModelPermissionOnResource.Raw | null;
        created_by: string;
        creation_time_unix: number;
        archived_time_unix?: number | null;
    }
}
