/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";

export const RenderStatus: core.serialization.Schema<serializers.RenderStatus.Raw, ElevenLabs.RenderStatus> =
    core.serialization.enum_(["complete", "processing", "failed"]);

export declare namespace RenderStatus {
    export type Raw = "complete" | "processing" | "failed";
}
