// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const RttStatusPayload: core.serialization.ObjectSchema<
    serializers.RttStatusPayload.Raw,
    ElevenLabs.RttStatusPayload
> = core.serialization.object({
    messageType: core.serialization.property("message_type", core.serialization.stringLiteral("status")),
    status: core.serialization.string(),
});

export declare namespace RttStatusPayload {
    export interface Raw {
        message_type: "status";
        status: string;
    }
}
