// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SayNodePromptMessageInput: core.serialization.ObjectSchema<
    serializers.SayNodePromptMessageInput.Raw,
    ElevenLabs.SayNodePromptMessageInput
> = core.serialization.object({
    type: core.serialization.stringLiteral("prompt").optional(),
    prompt: core.serialization.string(),
});

export declare namespace SayNodePromptMessageInput {
    export interface Raw {
        type?: "prompt" | null;
        prompt: string;
    }
}
