// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const ScribeWarning: core.serialization.ObjectSchema<serializers.ScribeWarning.Raw, ElevenLabs.ScribeWarning> =
    core.serialization.object({
        messageType: core.serialization.property("message_type", core.serialization.string().optional()),
        warning: core.serialization.string(),
    });

export declare namespace ScribeWarning {
    export interface Raw {
        message_type?: string | null;
        warning: string;
    }
}
