// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const SeatType: core.serialization.Schema<serializers.SeatType.Raw, ElevenLabs.SeatType> =
    core.serialization.enum_(["workspace_admin", "workspace_member", "workspace_lite_member"]);

export declare namespace SeatType {
    export type Raw = "workspace_admin" | "workspace_member" | "workspace_lite_member";
}
