// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const SendCustomEmailParams: core.serialization.ObjectSchema<
    serializers.SendCustomEmailParams.Raw,
    ElevenLabs.SendCustomEmailParams
> = core.serialization.object({
    smbToolType: core.serialization.property(
        "smb_tool_type",
        core.serialization.stringLiteral("send_custom_email").optional(),
    ),
});

export declare namespace SendCustomEmailParams {
    export interface Raw {
        smb_tool_type?: "send_custom_email" | null;
    }
}
