// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SfxModelId: core.serialization.Schema<serializers.SfxModelId.Raw, ElevenLabs.SfxModelId> =
    core.serialization.stringLiteral("eleven_text_to_sound_v2");

export declare namespace SfxModelId {
    export type Raw = "eleven_text_to_sound_v2";
}
