// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";

export const SingleUseTokenType: core.serialization.Schema<
    serializers.SingleUseTokenType.Raw,
    ElevenLabs.SingleUseTokenType
> = core.serialization.stringLiteral("realtime_scribe");

export declare namespace SingleUseTokenType {
    export type Raw = "realtime_scribe";
}
