// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const SmbClientAccessConfig: core.serialization.ObjectSchema<
    serializers.SmbClientAccessConfig.Raw,
    ElevenLabs.SmbClientAccessConfig
> = core.serialization.object({
    enableSecureMode: core.serialization.property("enable_secure_mode", core.serialization.boolean().optional()),
    identityVerificationEnabled: core.serialization.property(
        "identity_verification_enabled",
        core.serialization.boolean().optional(),
    ),
    identityVerificationEmailEnabled: core.serialization.property(
        "identity_verification_email_enabled",
        core.serialization.boolean().optional(),
    ),
    identityVerificationSmsEnabled: core.serialization.property(
        "identity_verification_sms_enabled",
        core.serialization.boolean().optional(),
    ),
});

export declare namespace SmbClientAccessConfig {
    export interface Raw {
        enable_secure_mode?: boolean | null;
        identity_verification_enabled?: boolean | null;
        identity_verification_email_enabled?: boolean | null;
        identity_verification_sms_enabled?: boolean | null;
    }
}
