// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { DubbingMediaReference } from "./DubbingMediaReference";

export const SpeakerTrack: core.serialization.ObjectSchema<serializers.SpeakerTrack.Raw, ElevenLabs.SpeakerTrack> =
    core.serialization.object({
        id: core.serialization.string(),
        mediaRef: core.serialization.property("media_ref", DubbingMediaReference),
        speakerName: core.serialization.property("speaker_name", core.serialization.string()),
        voices: core.serialization.record(core.serialization.string(), core.serialization.string()),
        segments: core.serialization.list(core.serialization.string()),
    });

export declare namespace SpeakerTrack {
    export interface Raw {
        id: string;
        media_ref: DubbingMediaReference.Raw;
        speaker_name: string;
        voices: Record<string, string>;
        segments: string[];
    }
}
