// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const SpeechToTextWebhookResponseModel: core.serialization.ObjectSchema<
    serializers.SpeechToTextWebhookResponseModel.Raw,
    ElevenLabs.SpeechToTextWebhookResponseModel
> = core.serialization.object({
    message: core.serialization.string(),
    requestId: core.serialization.property("request_id", core.serialization.string()),
    transcriptionId: core.serialization.property("transcription_id", core.serialization.string().optional()),
});

export declare namespace SpeechToTextWebhookResponseModel {
    export interface Raw {
        message: string;
        request_id: string;
        transcription_id?: string | null;
    }
}
