// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const SpeechEngineConversationInitiationClientDataConfig: core.serialization.ObjectSchema<
    serializers.SpeechEngineConversationInitiationClientDataConfig.Raw,
    ElevenLabs.SpeechEngineConversationInitiationClientDataConfig
> = core.serialization.object({
    firstMessage: core.serialization.property("first_message", core.serialization.boolean().optional()),
});

export declare namespace SpeechEngineConversationInitiationClientDataConfig {
    export interface Raw {
        first_message?: boolean | null;
    }
}
