// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { ResourceAccessInfo } from "./ResourceAccessInfo";

export const SpeechEngineSummaryResponse: core.serialization.ObjectSchema<
    serializers.SpeechEngineSummaryResponse.Raw,
    ElevenLabs.SpeechEngineSummaryResponse
> = core.serialization.object({
    speechEngineId: core.serialization.property("speech_engine_id", core.serialization.string()),
    name: core.serialization.string(),
    createdAtUnixSecs: core.serialization.property("created_at_unix_secs", core.serialization.number()),
    tags: core.serialization.list(core.serialization.string()),
    accessInfo: core.serialization.property("access_info", ResourceAccessInfo),
});

export declare namespace SpeechEngineSummaryResponse {
    export interface Raw {
        speech_engine_id: string;
        name: string;
        created_at_unix_secs: number;
        tags: string[];
        access_info: ResourceAccessInfo.Raw;
    }
}
