// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";

export const SubscriptionResponseModelCharacterRefreshPeriod: core.serialization.Schema<
    serializers.SubscriptionResponseModelCharacterRefreshPeriod.Raw,
    ElevenLabs.SubscriptionResponseModelCharacterRefreshPeriod
> = core.serialization.enum_(["monthly_period", "annual_period"]);

export declare namespace SubscriptionResponseModelCharacterRefreshPeriod {
    export type Raw = "monthly_period" | "annual_period";
}
