// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { DynamicVariableAssignment } from "./DynamicVariableAssignment";
import { SystemToolConfigOutputParams } from "./SystemToolConfigOutputParams";
import { ToolCallSoundBehavior } from "./ToolCallSoundBehavior";
import { ToolCallSoundType } from "./ToolCallSoundType";
import { ToolErrorHandlingMode } from "./ToolErrorHandlingMode";

export const SystemToolConfigOutput: core.serialization.ObjectSchema<
    serializers.SystemToolConfigOutput.Raw,
    ElevenLabs.SystemToolConfigOutput
> = core.serialization.object({
    type: core.serialization.stringLiteral("system").optional(),
    name: core.serialization.string(),
    description: core.serialization.string().optional(),
    responseTimeoutSecs: core.serialization.property("response_timeout_secs", core.serialization.number().optional()),
    disableInterruptions: core.serialization.property("disable_interruptions", core.serialization.boolean().optional()),
    forcePreToolSpeech: core.serialization.property("force_pre_tool_speech", core.serialization.boolean().optional()),
    assignments: core.serialization.list(DynamicVariableAssignment).optional(),
    toolCallSound: core.serialization.property("tool_call_sound", ToolCallSoundType.optional()),
    toolCallSoundBehavior: core.serialization.property("tool_call_sound_behavior", ToolCallSoundBehavior.optional()),
    toolErrorHandlingMode: core.serialization.property("tool_error_handling_mode", ToolErrorHandlingMode.optional()),
    params: SystemToolConfigOutputParams,
});

export declare namespace SystemToolConfigOutput {
    export interface Raw {
        type?: "system" | null;
        name: string;
        description?: string | null;
        response_timeout_secs?: number | null;
        disable_interruptions?: boolean | null;
        force_pre_tool_speech?: boolean | null;
        assignments?: DynamicVariableAssignment.Raw[] | null;
        tool_call_sound?: ToolCallSoundType.Raw | null;
        tool_call_sound_behavior?: ToolCallSoundBehavior.Raw | null;
        tool_error_handling_mode?: ToolErrorHandlingMode.Raw | null;
        params: SystemToolConfigOutputParams.Raw;
    }
}
