// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TextToSpeechStreamRequest: core.serialization.Schema<
    serializers.TextToSpeechStreamRequest.Raw,
    ElevenLabs.TextToSpeechStreamRequest
> = core.serialization.unknown();

export declare namespace TextToSpeechStreamRequest {
    export type Raw = unknown;
}
