// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TextToDialogueMultiClientMessagePronunciationDictionaryLocatorsItem: core.serialization.ObjectSchema<
    serializers.TextToDialogueMultiClientMessagePronunciationDictionaryLocatorsItem.Raw,
    ElevenLabs.TextToDialogueMultiClientMessagePronunciationDictionaryLocatorsItem
> = core.serialization.object({
    pronunciationDictionaryId: core.serialization.property("pronunciation_dictionary_id", core.serialization.string()),
    versionId: core.serialization.property("version_id", core.serialization.string()),
});

export declare namespace TextToDialogueMultiClientMessagePronunciationDictionaryLocatorsItem {
    export interface Raw {
        pronunciation_dictionary_id: string;
        version_id: string;
    }
}
