// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const TextToDialogueWebsocketError: core.serialization.ObjectSchema<
    serializers.TextToDialogueWebsocketError.Raw,
    ElevenLabs.TextToDialogueWebsocketError
> = core.serialization.object({
    message: core.serialization.string(),
    error: core.serialization.string(),
    code: core.serialization.number(),
    param: core.serialization.string().optional(),
});

export declare namespace TextToDialogueWebsocketError {
    export interface Raw {
        message: string;
        error: string;
        code: number;
        param?: string | null;
    }
}
