// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { ElevenFlashV25Request } from "./ElevenFlashV25Request";
import { ElevenMultilingualV2Request } from "./ElevenMultilingualV2Request";
import { ElevenV3Request } from "./ElevenV3Request";

export const TextToSpeechGenerationRequest: core.serialization.Schema<
    serializers.TextToSpeechGenerationRequest.Raw,
    ElevenLabs.TextToSpeechGenerationRequest
> = core.serialization
    .union(core.serialization.discriminant("modelId", "model_id"), {
        eleven_flash_v2_5: ElevenFlashV25Request,
        eleven_multilingual_v2: ElevenMultilingualV2Request,
        eleven_v3: ElevenV3Request,
    })
    .transform<ElevenLabs.TextToSpeechGenerationRequest>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace TextToSpeechGenerationRequest {
    export type Raw =
        | TextToSpeechGenerationRequest.ElevenFlashV25
        | TextToSpeechGenerationRequest.ElevenMultilingualV2
        | TextToSpeechGenerationRequest.ElevenV3;

    export interface ElevenFlashV25 extends ElevenFlashV25Request.Raw {
        model_id: "eleven_flash_v2_5";
    }

    export interface ElevenMultilingualV2 extends ElevenMultilingualV2Request.Raw {
        model_id: "eleven_multilingual_v2";
    }

    export interface ElevenV3 extends ElevenV3Request.Raw {
        model_id: "eleven_v3";
    }
}
