// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const TextToDialogueWebsocketApplyTextNormalizationEnum: core.serialization.Schema<
    serializers.TextToDialogueWebsocketApplyTextNormalizationEnum.Raw,
    ElevenLabs.TextToDialogueWebsocketApplyTextNormalizationEnum
> = core.serialization.enum_(["on", "off"]);

export declare namespace TextToDialogueWebsocketApplyTextNormalizationEnum {
    export type Raw = "on" | "off";
}
