// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const ThresholdGuardrail: core.serialization.ObjectSchema<
    serializers.ThresholdGuardrail.Raw,
    ElevenLabs.ThresholdGuardrail
> = core.serialization.object({
    isEnabled: core.serialization.property("is_enabled", core.serialization.boolean().optional()),
    threshold: core.serialization.number().optional(),
});

export declare namespace ThresholdGuardrail {
    export interface Raw {
        is_enabled?: boolean | null;
        threshold?: number | null;
    }
}
