// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const TokenResponseModel: core.serialization.ObjectSchema<
    serializers.TokenResponseModel.Raw,
    ElevenLabs.TokenResponseModel
> = core.serialization.object({
    token: core.serialization.string(),
});

export declare namespace TokenResponseModel {
    export interface Raw {
        token: string;
    }
}
