// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ToolType: core.serialization.Schema<serializers.ToolType.Raw, ElevenLabs.ToolType> =
    core.serialization.enum_([
        "system",
        "webhook",
        "client",
        "mcp",
        "workflow",
        "api_integration_webhook",
        "api_integration_mcp",
        "smb",
    ]);

export declare namespace ToolType {
    export type Raw =
        | "system"
        | "webhook"
        | "client"
        | "mcp"
        | "workflow"
        | "api_integration_webhook"
        | "api_integration_mcp"
        | "smb";
}
