// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TranslateAudioOutputError: core.serialization.ObjectSchema<
    serializers.TranslateAudioOutputError.Raw,
    ElevenLabs.TranslateAudioOutputError
> = core.serialization.object({
    messageType: core.serialization.property("message_type", core.serialization.stringLiteral("audio_output_error")),
    error: core.serialization.string(),
});

export declare namespace TranslateAudioOutputError {
    export interface Raw {
        message_type: "audio_output_error";
        error: string;
    }
}
