// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";

export const TtsOptimizeStreamingLatency: core.serialization.Schema<
    serializers.TtsOptimizeStreamingLatency.Raw,
    ElevenLabs.TtsOptimizeStreamingLatency
> = core.serialization.number();

export declare namespace TtsOptimizeStreamingLatency {
    export type Raw = number;
}
