// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const UpdateChapterRequest: core.serialization.Schema<
    serializers.UpdateChapterRequest.Raw,
    ElevenLabs.UpdateChapterRequest
> = core.serialization.unknown();

export declare namespace UpdateChapterRequest {
    export type Raw = unknown;
}
