// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const UsageAggregationInterval: core.serialization.Schema<
    serializers.UsageAggregationInterval.Raw,
    ElevenLabs.UsageAggregationInterval
> = core.serialization.enum_(["hour", "day", "week", "month", "cumulative"]);

export declare namespace UsageAggregationInterval {
    export type Raw = "hour" | "day" | "week" | "month" | "cumulative";
}
