// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const VideoKeyMoment: core.serialization.ObjectSchema<
    serializers.VideoKeyMoment.Raw,
    ElevenLabs.VideoKeyMoment
> = core.serialization.object({
    timestampMs: core.serialization.property("timestamp_ms", core.serialization.number()),
    type: core.serialization.string(),
    description: core.serialization.string(),
});

export declare namespace VideoKeyMoment {
    export interface Raw {
        timestamp_ms: number;
        type: string;
        description: string;
    }
}
