// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { VerificationAttemptResponse } from "./VerificationAttemptResponse";

export const VoiceVerificationResponse: core.serialization.ObjectSchema<
    serializers.VoiceVerificationResponse.Raw,
    ElevenLabs.VoiceVerificationResponse
> = core.serialization.object({
    requiresVerification: core.serialization.property("requires_verification", core.serialization.boolean()),
    isVerified: core.serialization.property("is_verified", core.serialization.boolean()),
    verificationFailures: core.serialization.property(
        "verification_failures",
        core.serialization.list(core.serialization.string()),
    ),
    verificationAttemptsCount: core.serialization.property("verification_attempts_count", core.serialization.number()),
    language: core.serialization.string().optional(),
    verificationAttempts: core.serialization.property(
        "verification_attempts",
        core.serialization.list(VerificationAttemptResponse).optional(),
    ),
});

export declare namespace VoiceVerificationResponse {
    export interface Raw {
        requires_verification: boolean;
        is_verified: boolean;
        verification_failures: string[];
        verification_attempts_count: number;
        language?: string | null;
        verification_attempts?: VerificationAttemptResponse.Raw[] | null;
    }
}
