// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const VoiceCategory: core.serialization.Schema<serializers.VoiceCategory.Raw, ElevenLabs.VoiceCategory> =
    core.serialization.enum_(["generated", "cloned", "premade", "professional", "famous", "high_quality"]);

export declare namespace VoiceCategory {
    export type Raw = "generated" | "cloned" | "premade" | "professional" | "famous" | "high_quality";
}
