// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { ConvAiDynamicVariable } from "./ConvAiDynamicVariable";
import { ConvAiSecretLocator } from "./ConvAiSecretLocator";

export const WebhookToolApiSchemaConfigInputRequestHeadersValue: core.serialization.Schema<
    serializers.WebhookToolApiSchemaConfigInputRequestHeadersValue.Raw,
    ElevenLabs.WebhookToolApiSchemaConfigInputRequestHeadersValue
> = core.serialization.undiscriminatedUnion([core.serialization.string(), ConvAiSecretLocator, ConvAiDynamicVariable]);

export declare namespace WebhookToolApiSchemaConfigInputRequestHeadersValue {
    export type Raw = string | ConvAiSecretLocator.Raw | ConvAiDynamicVariable.Raw;
}
