/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import { WebhookToolApiSchemaConfigInputMethod } from "./WebhookToolApiSchemaConfigInputMethod";
import { LiteralJsonSchemaProperty } from "./LiteralJsonSchemaProperty";
import { QueryParamsJsonSchema } from "./QueryParamsJsonSchema";
import { WebhookToolApiSchemaConfigInputRequestHeadersValue } from "./WebhookToolApiSchemaConfigInputRequestHeadersValue";

export const WebhookToolApiSchemaConfigInput: core.serialization.ObjectSchema<
    serializers.WebhookToolApiSchemaConfigInput.Raw,
    ElevenLabs.WebhookToolApiSchemaConfigInput
> = core.serialization.object({
    url: core.serialization.string(),
    method: WebhookToolApiSchemaConfigInputMethod.optional(),
    pathParamsSchema: core.serialization.property(
        "path_params_schema",
        core.serialization.record(core.serialization.string(), LiteralJsonSchemaProperty).optional(),
    ),
    queryParamsSchema: core.serialization.property("query_params_schema", QueryParamsJsonSchema.optional()),
    requestBodySchema: core.serialization.property(
        "request_body_schema",
        core.serialization.lazyObject(() => serializers.ObjectJsonSchemaPropertyInput).optional(),
    ),
    requestHeaders: core.serialization.property(
        "request_headers",
        core.serialization
            .record(core.serialization.string(), WebhookToolApiSchemaConfigInputRequestHeadersValue)
            .optional(),
    ),
});

export declare namespace WebhookToolApiSchemaConfigInput {
    export interface Raw {
        url: string;
        method?: WebhookToolApiSchemaConfigInputMethod.Raw | null;
        path_params_schema?: Record<string, LiteralJsonSchemaProperty.Raw> | null;
        query_params_schema?: QueryParamsJsonSchema.Raw | null;
        request_body_schema?: serializers.ObjectJsonSchemaPropertyInput.Raw | null;
        request_headers?: Record<string, WebhookToolApiSchemaConfigInputRequestHeadersValue.Raw> | null;
    }
}
