// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const WebhookHmacSettings: core.serialization.ObjectSchema<
    serializers.WebhookHmacSettings.Raw,
    ElevenLabs.WebhookHmacSettings
> = core.serialization.object({
    authType: core.serialization.property("auth_type", core.serialization.stringLiteral("hmac")),
    name: core.serialization.string(),
    webhookUrl: core.serialization.property("webhook_url", core.serialization.string()),
    requestHeaders: core.serialization.property(
        "request_headers",
        core.serialization.record(core.serialization.string(), core.serialization.string().optional()).optional(),
    ),
});

export declare namespace WebhookHmacSettings {
    export interface Raw {
        auth_type: "hmac";
        name: string;
        webhook_url: string;
        request_headers?: Record<string, string | null | undefined> | null;
    }
}
