// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const WidgetConfigSyntaxHighlightTheme: core.serialization.Schema<
    serializers.WidgetConfigSyntaxHighlightTheme.Raw,
    ElevenLabs.WidgetConfigSyntaxHighlightTheme
> = core.serialization.enum_(["light", "dark"]);

export declare namespace WidgetConfigSyntaxHighlightTheme {
    export type Raw = "light" | "dark";
}
