/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import { WidgetTextContents } from "./WidgetTextContents";

export const WidgetLanguagePreset: core.serialization.ObjectSchema<
    serializers.WidgetLanguagePreset.Raw,
    ElevenLabs.WidgetLanguagePreset
> = core.serialization.object({
    textContents: core.serialization.property("text_contents", WidgetTextContents.optional()),
});

export declare namespace WidgetLanguagePreset {
    export interface Raw {
        text_contents?: WidgetTextContents.Raw | null;
    }
}
