// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { PostDialDigitsDynamicVariable } from "./PostDialDigitsDynamicVariable";
import { PostDialDigitsStatic } from "./PostDialDigitsStatic";

export const WorkflowPhoneNumberNodeModelInputPostDialDigits: core.serialization.Schema<
    serializers.WorkflowPhoneNumberNodeModelInputPostDialDigits.Raw,
    ElevenLabs.WorkflowPhoneNumberNodeModelInputPostDialDigits
> = core.serialization
    .union("type", {
        dynamic: PostDialDigitsDynamicVariable,
        static: PostDialDigitsStatic,
    })
    .transform<ElevenLabs.WorkflowPhoneNumberNodeModelInputPostDialDigits>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace WorkflowPhoneNumberNodeModelInputPostDialDigits {
    export type Raw =
        | WorkflowPhoneNumberNodeModelInputPostDialDigits.Dynamic
        | WorkflowPhoneNumberNodeModelInputPostDialDigits.Static;

    export interface Dynamic extends PostDialDigitsDynamicVariable.Raw {
        type: "dynamic";
    }

    export interface Static extends PostDialDigitsStatic.Raw {
        type: "static";
    }
}
