// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { PositionInput } from "./PositionInput.js";
import { TransferTypeEnum } from "./TransferTypeEnum.js";
import { UuiTransferConfig } from "./UuiTransferConfig.js";
import { WorkflowPhoneNumberNodeModelInputCustomSipHeadersItem } from "./WorkflowPhoneNumberNodeModelInputCustomSipHeadersItem.js";
import { WorkflowPhoneNumberNodeModelInputPostDialDigits } from "./WorkflowPhoneNumberNodeModelInputPostDialDigits.js";
import { WorkflowPhoneNumberNodeModelInputTransferDestination } from "./WorkflowPhoneNumberNodeModelInputTransferDestination.js";

export const WorkflowPhoneNumberNodeModelInput: core.serialization.ObjectSchema<
    serializers.WorkflowPhoneNumberNodeModelInput.Raw,
    ElevenLabs.WorkflowPhoneNumberNodeModelInput
> = core.serialization.object({
    customSipHeaders: core.serialization.property(
        "custom_sip_headers",
        core.serialization.list(WorkflowPhoneNumberNodeModelInputCustomSipHeadersItem).optional(),
    ),
    transferDestination: core.serialization.property(
        "transfer_destination",
        WorkflowPhoneNumberNodeModelInputTransferDestination,
    ),
    transferType: core.serialization.property("transfer_type", TransferTypeEnum.optional()),
    sipReferPlayDialtone: core.serialization.property(
        "sip_refer_play_dialtone",
        core.serialization.boolean().optional(),
    ),
    uui: UuiTransferConfig.optional(),
    postDialDigits: core.serialization.property(
        "post_dial_digits",
        WorkflowPhoneNumberNodeModelInputPostDialDigits.optional(),
    ),
    position: PositionInput.optional(),
    edgeOrder: core.serialization.property(
        "edge_order",
        core.serialization.list(core.serialization.string()).optional(),
    ),
});

export declare namespace WorkflowPhoneNumberNodeModelInput {
    export interface Raw {
        custom_sip_headers?: WorkflowPhoneNumberNodeModelInputCustomSipHeadersItem.Raw[] | null;
        transfer_destination: WorkflowPhoneNumberNodeModelInputTransferDestination.Raw;
        transfer_type?: TransferTypeEnum.Raw | null;
        sip_refer_play_dialtone?: boolean | null;
        uui?: UuiTransferConfig.Raw | null;
        post_dial_digits?: WorkflowPhoneNumberNodeModelInputPostDialDigits.Raw | null;
        position?: PositionInput.Raw | null;
        edge_order?: string[] | null;
    }
}
