// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../../../../../index";

/**
 * @example
 *     {
 *         dependentType: "direct",
 *         pageSize: 1,
 *         cursor: "cursor"
 *     }
 */
export interface DocumentsGetAgentsRequest {
    /** Type of dependent agents to return. */
    dependentType?: ElevenLabs.KnowledgeBaseDependentType;
    /** How many documents to return at maximum. Can not exceed 100, defaults to 30. */
    pageSize?: number;
    /** Used for fetching next page. Cursor is returned in the response. */
    cursor?: string;
}
