// This file was auto-generated by Fern from our API Definition.

import { ElevenLabsClient } from "../../../../src/Client";
import { mockServerPool } from "../../../mock-server/MockServerPool";

describe("DraftsClient", () => {
    test("create", async () => {
        const server = mockServerPool.createServer();
        const client = new ElevenLabsClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            conversation_config: { key: "value" },
            platform_settings: { key: "value" },
            workflow: {
                edges: {
                    entry_to_tool_a: {
                        source: "entry_node",
                        target: "tool_node_a",
                        forward_condition: {
                            type: "expression",
                            expression: { type: "and_operator", children: [{ type: "boolean_literal", value: true }] },
                        },
                    },
                    start_to_entry: {
                        source: "start_node",
                        target: "entry_node",
                        forward_condition: {
                            type: "expression",
                            expression: { type: "and_operator", children: [{ type: "boolean_literal", value: true }] },
                        },
                    },
                    tool_a_to_failure: {
                        source: "tool_node_a",
                        target: "failure_node",
                        forward_condition: {
                            type: "expression",
                            expression: { type: "and_operator", children: [{ type: "boolean_literal", value: true }] },
                        },
                    },
                    tool_a_to_tool_b: {
                        source: "tool_node_a",
                        target: "tool_node_b",
                        forward_condition: {
                            type: "expression",
                            expression: { type: "and_operator", children: [{ type: "boolean_literal", value: true }] },
                        },
                    },
                    tool_b_to_agent_transfer: {
                        source: "tool_node_b",
                        target: "success_transfer",
                        forward_condition: {
                            type: "expression",
                            expression: { type: "and_operator", children: [{ type: "boolean_literal", value: true }] },
                        },
                    },
                    tool_b_to_conversation: {
                        source: "tool_node_b",
                        target: "success_conversation",
                        forward_condition: {
                            type: "expression",
                            expression: { type: "and_operator", children: [{ type: "boolean_literal", value: true }] },
                        },
                    },
                    tool_b_to_end: {
                        source: "tool_node_b",
                        target: "success_end",
                        forward_condition: {
                            type: "expression",
                            expression: { type: "and_operator", children: [{ type: "boolean_literal", value: true }] },
                        },
                    },
                    tool_b_to_phone: {
                        source: "tool_node_b",
                        target: "success_phone",
                        forward_condition: {
                            type: "expression",
                            expression: { type: "and_operator", children: [{ type: "boolean_literal", value: true }] },
                        },
                    },
                },
                nodes: {
                    entry_node: { type: "end" },
                    failure_node: { type: "end" },
                    start_node: { type: "end" },
                    success_conversation: { type: "end" },
                    success_end: { type: "end" },
                    success_phone: { type: "end" },
                    success_transfer: { type: "end" },
                    tool_node_a: { type: "end" },
                    tool_node_b: { type: "end" },
                },
            },
            name: "name",
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/convai/agents/agent_3701k3ttaq12ewp8b7qv5rfyszkz/drafts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.conversationalAi.agents.drafts.create("agent_3701k3ttaq12ewp8b7qv5rfyszkz", {
            branchId: "agtbrch_8901k4t9z5defmb8vh3e9361y7nj",
            conversationConfig: {
                key: "value",
            },
            platformSettings: {
                key: "value",
            },
            workflow: {
                edges: {
                    entry_to_tool_a: {
                        source: "entry_node",
                        target: "tool_node_a",
                        forwardCondition: {
                            type: "expression",
                            expression: {
                                type: "and_operator",
                                children: [
                                    {
                                        type: "boolean_literal",
                                        value: true,
                                    },
                                ],
                            },
                        },
                    },
                    start_to_entry: {
                        source: "start_node",
                        target: "entry_node",
                        forwardCondition: {
                            type: "expression",
                            expression: {
                                type: "and_operator",
                                children: [
                                    {
                                        type: "boolean_literal",
                                        value: true,
                                    },
                                ],
                            },
                        },
                    },
                    tool_a_to_failure: {
                        source: "tool_node_a",
                        target: "failure_node",
                        forwardCondition: {
                            type: "expression",
                            expression: {
                                type: "and_operator",
                                children: [
                                    {
                                        type: "boolean_literal",
                                        value: true,
                                    },
                                ],
                            },
                        },
                    },
                    tool_a_to_tool_b: {
                        source: "tool_node_a",
                        target: "tool_node_b",
                        forwardCondition: {
                            type: "expression",
                            expression: {
                                type: "and_operator",
                                children: [
                                    {
                                        type: "boolean_literal",
                                        value: true,
                                    },
                                ],
                            },
                        },
                    },
                    tool_b_to_agent_transfer: {
                        source: "tool_node_b",
                        target: "success_transfer",
                        forwardCondition: {
                            type: "expression",
                            expression: {
                                type: "and_operator",
                                children: [
                                    {
                                        type: "boolean_literal",
                                        value: true,
                                    },
                                ],
                            },
                        },
                    },
                    tool_b_to_conversation: {
                        source: "tool_node_b",
                        target: "success_conversation",
                        forwardCondition: {
                            type: "expression",
                            expression: {
                                type: "and_operator",
                                children: [
                                    {
                                        type: "boolean_literal",
                                        value: true,
                                    },
                                ],
                            },
                        },
                    },
                    tool_b_to_end: {
                        source: "tool_node_b",
                        target: "success_end",
                        forwardCondition: {
                            type: "expression",
                            expression: {
                                type: "and_operator",
                                children: [
                                    {
                                        type: "boolean_literal",
                                        value: true,
                                    },
                                ],
                            },
                        },
                    },
                    tool_b_to_phone: {
                        source: "tool_node_b",
                        target: "success_phone",
                        forwardCondition: {
                            type: "expression",
                            expression: {
                                type: "and_operator",
                                children: [
                                    {
                                        type: "boolean_literal",
                                        value: true,
                                    },
                                ],
                            },
                        },
                    },
                },
                nodes: {
                    entry_node: {
                        type: "end",
                    },
                    failure_node: {
                        type: "end",
                    },
                    start_node: {
                        type: "end",
                    },
                    success_conversation: {
                        type: "end",
                    },
                    success_end: {
                        type: "end",
                    },
                    success_phone: {
                        type: "end",
                    },
                    success_transfer: {
                        type: "end",
                    },
                    tool_node_a: {
                        type: "end",
                    },
                    tool_node_b: {
                        type: "end",
                    },
                },
            },
            name: "name",
        });
        expect(response).toEqual({
            key: "value",
        });
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        const client = new ElevenLabsClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/v1/convai/agents/agent_3701k3ttaq12ewp8b7qv5rfyszkz/drafts")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.conversationalAi.agents.drafts.delete("agent_3701k3ttaq12ewp8b7qv5rfyszkz", {
            branchId: "agtbrch_8901k4t9z5defmb8vh3e9361y7nj",
        });
        expect(response).toEqual({
            key: "value",
        });
    });
});
