// This file was auto-generated by Fern from our API Definition.

import * as ElevenLabs from "../../../../src/api/index";
import { ElevenLabsClient } from "../../../../src/Client";
import { mockServerPool } from "../../../mock-server/MockServerPool";

describe("SummariesClient", () => {
    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ElevenLabsClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            string: {
                status: "success",
                data: {
                    agent_id: "agent_id",
                    name: "name",
                    tags: ["tags", "tags"],
                    created_at_unix_secs: 1,
                    access_info: {
                        is_creator: true,
                        creator_name: "creator_name",
                        creator_email: "creator_email",
                        role: "admin",
                    },
                    last_call_time_unix_secs: 1,
                    archived: true,
                },
            },
        };
        server
            .mockEndpoint()
            .get("/v1/convai/agents/summaries")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.conversationalAi.agents.summaries.get();
        expect(response).toEqual({
            string: {
                status: "success",
                data: {
                    agentId: "agent_id",
                    name: "name",
                    tags: ["tags", "tags"],
                    createdAtUnixSecs: 1,
                    accessInfo: {
                        isCreator: true,
                        creatorName: "creator_name",
                        creatorEmail: "creator_email",
                        role: "admin",
                    },
                    lastCallTimeUnixSecs: 1,
                    archived: true,
                },
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ElevenLabsClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/v1/convai/agents/summaries")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.conversationalAi.agents.summaries.get();
        }).rejects.toThrow(ElevenLabs.UnprocessableEntityError);
    });
});
