/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as ElevenLabs from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import { McpApprovalPolicy } from "../../../../../../types/McpApprovalPolicy";

export const McpServerConfigUpdateRequestModel: core.serialization.Schema<
    serializers.conversationalAi.McpServerConfigUpdateRequestModel.Raw,
    ElevenLabs.conversationalAi.McpServerConfigUpdateRequestModel
> = core.serialization.object({
    approvalPolicy: core.serialization.property("approval_policy", McpApprovalPolicy.optional()),
    forcePreToolSpeech: core.serialization.property("force_pre_tool_speech", core.serialization.boolean().optional()),
});

export declare namespace McpServerConfigUpdateRequestModel {
    export interface Raw {
        approval_policy?: McpApprovalPolicy.Raw | null;
        force_pre_tool_speech?: boolean | null;
    }
}
