// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import type * as serializers from "../../../../../index.js";
import { UpdateResponseUnitTestRequest } from "../../../../../types/UpdateResponseUnitTestRequest.js";
import { UpdateSimulationTestRequest } from "../../../../../types/UpdateSimulationTestRequest.js";
import { UpdateToolCallUnitTestRequest } from "../../../../../types/UpdateToolCallUnitTestRequest.js";

export const UpdateTestsRequestBody: core.serialization.Schema<
    serializers.agents.UpdateTestsRequestBody.Raw,
    ElevenLabs.agents.UpdateTestsRequestBody
> = core.serialization
    .union("type", {
        llm: UpdateResponseUnitTestRequest,
        tool: UpdateToolCallUnitTestRequest,
        simulation: UpdateSimulationTestRequest,
    })
    .transform<ElevenLabs.agents.UpdateTestsRequestBody>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace UpdateTestsRequestBody {
    export type Raw = UpdateTestsRequestBody.Llm | UpdateTestsRequestBody.Tool | UpdateTestsRequestBody.Simulation;

    export interface Llm extends UpdateResponseUnitTestRequest.Raw {
        type: "llm";
    }

    export interface Tool extends UpdateToolCallUnitTestRequest.Raw {
        type: "tool";
    }

    export interface Simulation extends UpdateSimulationTestRequest.Raw {
        type: "simulation";
    }
}
