/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ElevenLabs from "../../../../api/index";
import * as core from "../../../../core";

export const BodyTextToSpeechStreamingV1TextToSpeechVoiceIdStreamPostApplyTextNormalization: core.serialization.Schema<
    serializers.BodyTextToSpeechStreamingV1TextToSpeechVoiceIdStreamPostApplyTextNormalization.Raw,
    ElevenLabs.BodyTextToSpeechStreamingV1TextToSpeechVoiceIdStreamPostApplyTextNormalization
> = core.serialization.enum_(["auto", "on", "off"]);

export declare namespace BodyTextToSpeechStreamingV1TextToSpeechVoiceIdStreamPostApplyTextNormalization {
    export type Raw = "auto" | "on" | "off";
}
