// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../index";

/**
 * Defines the message types that can be received by the client from the server
 */
export type ReceiveTranscription =
    | ElevenLabs.SessionStartedPayload
    | ElevenLabs.PartialTranscriptPayload
    | ElevenLabs.FinalTranscript
    | ElevenLabs.FinalTranscriptWithTimestamps
    | ElevenLabs.CommittedTranscriptPayload
    | ElevenLabs.CommittedTranscriptWithTimestampsPayload
    | ElevenLabs.CommittedTranscriptEntitiesPayload
    | ElevenLabs.ScribeErrorPayload
    | ElevenLabs.ScribeAuthErrorPayload
    | ElevenLabs.ScribeQuotaExceededErrorPayload
    | ElevenLabs.ScribeThrottledErrorPayload
    | ElevenLabs.ScribeUnacceptedTermsErrorPayload
    | ElevenLabs.ScribeRateLimitedErrorPayload
    | ElevenLabs.ScribeQueueOverflowErrorPayload
    | ElevenLabs.ScribeResourceExhaustedErrorPayload
    | ElevenLabs.ScribeSessionTimeLimitExceededErrorPayload
    | ElevenLabs.ScribeInputErrorPayload
    | ElevenLabs.ScribeChunkSizeExceededErrorPayload
    | ElevenLabs.ScribeInsufficientAudioActivityErrorPayload
    | ElevenLabs.ScribeTranscriberErrorPayload;
