// This file was auto-generated by Fern from our API Definition.

/** Strategy for committing transcriptions. */
export const TextToSpeechCommitStrategy = {
    Manual: "manual",
    Vad: "vad",
} as const;
export type TextToSpeechCommitStrategy = (typeof TextToSpeechCommitStrategy)[keyof typeof TextToSpeechCommitStrategy];
