// This file was auto-generated by Fern from our API Definition.

import { ElevenLabsClient } from "../../../../src/Client";
import { mockServerPool } from "../../../mock-server/MockServerPool";

describe("InvocationsClient", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new ElevenLabsClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            meta: { total: 1, page: 1, page_size: 1 },
            results: [
                {
                    id: "id",
                    agent_id: "agent_id",
                    branch_id: "branch_id",
                    created_at_unix_secs: 1,
                    test_run_count: 1,
                    passed_count: 1,
                    failed_count: 1,
                    pending_count: 1,
                    title: "title",
                    access_info: {
                        is_creator: true,
                        creator_name: "John Doe",
                        creator_email: "john.doe@example.com",
                        role: "admin",
                    },
                },
            ],
            next_cursor: "next_cursor",
            has_more: true,
        };
        server
            .mockEndpoint()
            .get("/v1/convai/test-invocations")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.conversationalAi.tests.invocations.list({
            agentId: "agent_id",
            pageSize: 1,
            cursor: "cursor",
        });
        expect(response).toEqual({
            meta: {
                total: 1,
                page: 1,
                pageSize: 1,
            },
            results: [
                {
                    id: "id",
                    agentId: "agent_id",
                    branchId: "branch_id",
                    createdAtUnixSecs: 1,
                    testRunCount: 1,
                    passedCount: 1,
                    failedCount: 1,
                    pendingCount: 1,
                    title: "title",
                    accessInfo: {
                        isCreator: true,
                        creatorName: "John Doe",
                        creatorEmail: "john.doe@example.com",
                        role: "admin",
                    },
                },
            ],
            nextCursor: "next_cursor",
            hasMore: true,
        });
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new ElevenLabsClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            agent_id: "agent_id",
            branch_id: "branch_id",
            created_at: 1,
            test_runs: [
                {
                    test_run_id: "test_run_id",
                    test_info: {
                        chat_history: [{ role: "user", time_in_call_secs: 1 }],
                        success_condition: "success_condition",
                        success_examples: [{ response: "response", type: "success" }],
                        failure_examples: [{ response: "response", type: "failure" }],
                    },
                    test_invocation_id: "test_invocation_id",
                    agent_id: "agent_id",
                    branch_id: "branch_id",
                    workflow_node_id: "workflow_node_id",
                    status: "pending",
                    agent_responses: [{ role: "user", time_in_call_secs: 1 }],
                    test_id: "test_id",
                    test_name: "test_name",
                    condition_result: { result: "success" },
                    last_updated_at_unix: 1,
                    metadata: {
                        workspace_id: "workspace_id",
                        test_name: "test_name",
                        ran_by_user_email: "ran_by_user_email",
                    },
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/v1/convai/test-invocations/test_invocation_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.conversationalAi.tests.invocations.get("test_invocation_id");
        expect(response).toEqual({
            id: "id",
            agentId: "agent_id",
            branchId: "branch_id",
            createdAt: 1,
            testRuns: [
                {
                    testRunId: "test_run_id",
                    testInfo: {
                        chatHistory: [
                            {
                                role: "user",
                                timeInCallSecs: 1,
                            },
                        ],
                        successCondition: "success_condition",
                        successExamples: [
                            {
                                response: "response",
                                type: "success",
                            },
                        ],
                        failureExamples: [
                            {
                                response: "response",
                                type: "failure",
                            },
                        ],
                    },
                    testInvocationId: "test_invocation_id",
                    agentId: "agent_id",
                    branchId: "branch_id",
                    workflowNodeId: "workflow_node_id",
                    status: "pending",
                    agentResponses: [
                        {
                            role: "user",
                            timeInCallSecs: 1,
                        },
                    ],
                    testId: "test_id",
                    testName: "test_name",
                    conditionResult: {
                        result: "success",
                    },
                    lastUpdatedAtUnix: 1,
                    metadata: {
                        workspaceId: "workspace_id",
                        testName: "test_name",
                        ranByUserEmail: "ran_by_user_email",
                    },
                },
            ],
        });
    });

    test("resubmit", async () => {
        const server = mockServerPool.createServer();
        const client = new ElevenLabsClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { test_run_ids: ["test_run_ids"], agent_id: "agent_id" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/convai/test-invocations/test_invocation_id/resubmit")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.conversationalAi.tests.invocations.resubmit("test_invocation_id", {
            testRunIds: ["test_run_ids"],
            agentId: "agent_id",
        });
        expect(response).toEqual({
            key: "value",
        });
    });
});
