/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PronunciationDictionariesCreateFromFileRequestWorkspaceAccess = "admin" | "editor" | "viewer";
export const PronunciationDictionariesCreateFromFileRequestWorkspaceAccess = {
    Admin: "admin",
    Editor: "editor",
    Viewer: "viewer",
} as const;
