// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { ReceiveMessageMulti } from "../../types/ReceiveMessageMulti.js";

export const TextToSpeechSocketResponse: core.serialization.Schema<
    serializers.TextToSpeechSocketResponse.Raw,
    ElevenLabs.ReceiveMessageMulti
> = core.serialization.undiscriminatedUnion([ReceiveMessageMulti]);

export declare namespace TextToSpeechSocketResponse {
    export type Raw = ReceiveMessageMulti.Raw;
}
