// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../../../index";

/**
 * @example
 *     {
 *         startTime: 1,
 *         endTime: 1
 *     }
 */
export interface BodyGetWorkspaceUsageV1WorkspaceAnalyticsQueryUsageByProductOverTimePost {
    startTime: number;
    endTime: number;
    intervalSeconds?: number;
    groupBy?: ElevenLabs.workspace.BodyGetWorkspaceUsageV1WorkspaceAnalyticsQueryUsageByProductOverTimePostGroupByItem[];
    filters?: ElevenLabs.ColumnFilter[];
}
