// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import type * as serializers from "../../../../../../index";
import { MusicPrompt } from "../../../../../../types/MusicPrompt";

export const BodyGenerateCompositionPlanV1MusicPlanPost: core.serialization.Schema<
    serializers.music.BodyGenerateCompositionPlanV1MusicPlanPost.Raw,
    ElevenLabs.music.BodyGenerateCompositionPlanV1MusicPlanPost
> = core.serialization.object({
    prompt: core.serialization.string(),
    musicLengthMs: core.serialization.property("music_length_ms", core.serialization.number().optional()),
    sourceCompositionPlan: core.serialization.property("source_composition_plan", MusicPrompt.optional()),
    modelId: core.serialization.property("model_id", core.serialization.stringLiteral("music_v1").optional()),
});

export declare namespace BodyGenerateCompositionPlanV1MusicPlanPost {
    export interface Raw {
        prompt: string;
        music_length_ms?: number | null;
        source_composition_plan?: MusicPrompt.Raw | null;
        model_id?: "music_v1" | null;
    }
}
