/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type BodyCreatePodcastV1StudioPodcastsPostApplyTextNormalization = "auto" | "on" | "off" | "apply_english";
export const BodyCreatePodcastV1StudioPodcastsPostApplyTextNormalization = {
    Auto: "auto",
    On: "on",
    Off: "off",
    ApplyEnglish: "apply_english",
} as const;
