/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AudioIsolationStreamRequestFileFormat = "pcm_s16le_16" | "other";
export const AudioIsolationStreamRequestFileFormat = {
    PcmS16Le16: "pcm_s16le_16",
    Other: "other",
} as const;
