// This file was auto-generated by Fern from our API Definition.

import type * as ElevenLabs from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import type * as serializers from "../../../../../../index";
import { UpdateOrderRequest } from "../../../../../../types/UpdateOrderRequest";

export const BodyUpdateOrderV1ProductionsOrdersOrderIdPatch: core.serialization.Schema<
    serializers.productions.BodyUpdateOrderV1ProductionsOrdersOrderIdPatch.Raw,
    ElevenLabs.productions.BodyUpdateOrderV1ProductionsOrdersOrderIdPatch
> = core.serialization.object({
    request: UpdateOrderRequest,
});

export declare namespace BodyUpdateOrderV1ProductionsOrdersOrderIdPatch {
    export interface Raw {
        request: UpdateOrderRequest.Raw;
    }
}
